Citizen.CreateThread(function()

    AddTextEntry("WEAPON_AK47", "AK47")
    AddTextEntry("WEAPON_M4A1", "M4A1")
    AddTextEntry("WEAPON_M4A1FM", "M4A1 Custom")
    AddTextEntry("WEAPON_AK74", "AK74")
    AddTextEntry("WEAPON_L85A2", "L85A2")
    AddTextEntry("WEAPON_HONEYBADGER", "Honey Badger")
    AddTextEntry("WEAPON_M4A4", "Mk18")
    AddTextEntry("WEAPON_BIZON", "Bizon")
    AddTextEntry("WEAPON_ACR", "ACR")
    AddTextEntry("WEAPON_PROTORIFLE", "Coil Modern Modular Carbine")
    AddTextEntry("WEAPON_M870", "M870")
    AddTextEntry("WEAPON_SCARH", "SCAR")
    AddTextEntry("WEAPON_AUG", "AUG")
    AddTextEntry("WEAPON_AKP", "AK Draco")
    AddTextEntry("WEAPON_M16", "M16")
    AddTextEntry("WEAPON_BarrettM107CQ", "M107 Anti Material Rifle")
    AddTextEntry("WEAPON_Saiga12", "Saiga 12")
    AddTextEntry("WEAPON_1911", "SW1911")
    AddTextEntry("WEAPON_MP5A5", "MP5A5")
    AddTextEntry("WEAPON_PRECISIONCARBINE", "Precision Carbine")
    AddTextEntry("WEAPON_SPAS12", "SPAS 12")
    AddTextEntry("WEAPON_MAC10", "MAC 10")
    AddTextEntry("WEAPON_GLOCK18C", "Glock18C")
    AddTextEntry("WEAPON_Kar98k", "Kar98k")
    AddTextEntry("WEAPON_PROKOLOT", "Prokolot")
    AddTextEntry("WEAPON_M93", "M93")
    AddTextEntry("WEAPON_STG", "STG-44")
    AddTextEntry("WEAPON_RAZORBACK", "Razorback")
    AddTextEntry("WEAPON_WINCHESTER", "Winchester")
    AddTextEntry("WEAPON_ARX", "ARX160")
    AddTextEntry("WEAPON_UMP45", "UMP 45")
    AddTextEntry("WEAPON_VECTOR", "KV-45")
    AddTextEntry("WEAPON_PPSH", "PPSH-41")
    AddTextEntry("WEAPON_MP40", "MP-40")
    AddTextEntry("WEAPON_GLOCK", "Glock-17")
    AddTextEntry("WEAPON_NAMBU", "Nambu")
    AddTextEntry("WEAPON_LUGER", "P08 Luger")
    AddTextEntry("WEAPON_MG42", "MG 42")
    AddTextEntry("WEAPON_M60", "MG 60")
    AddTextEntry("WEAPON_SCARHDMR", "SCAR Marksman")
    AddTextEntry("WEAPON_Engraved1911", "Ornamental M1911")
    AddTextEntry("WEAPON_AWP", "AWP")
    AddTextEntry("WEAPON_SPRINGFIELD", "M1903")
    AddTextEntry("WEAPON_XM25", "XM-25")
    AddTextEntry("WEAPON_GRENADELAUNCHER_SMOKE", "Smoke Grenade Launcher")
    AddTextEntry("WEAPON_DEAGLE", "Desert Eagle")
    AddTextEntry("WEAPON_KATANA4", "Katana")
    AddTextEntry("WEAPON_MGA7000", "MGA Tomahawk")
    AddTextEntry("WEAPON_HORSEBAT", "Horse Bat")
    AddTextEntry("WEAPON_FLOWER_BOUQUET", "Flower Bouquet")
    AddTextEntry("WEAPON_Penetrator", "Penetrator")
    AddTextEntry("WEAPON_THROWINGKNIFE", "Throwing Knife")
    AddTextEntry("WEAPON_FN502", "P502")
    AddTextEntry("WEAPON_MP5SD", "MP5SD")
    AddTextEntry("WEAPON_CAR15", "CAR-15")
    AddTextEntry("WEAPON_MP9", "MP9")
    AddTextEntry("WEAPON_SigSauerMPX", "MPX")
    AddTextEntry("WEAPON_FNL1A1", "SLR")
    AddTextEntry("WEAPON_MDR", "MDR 556x45")
    AddTextEntry("WEAPON_MDR2", "MDR 7.62x51")


    -- Mags

    AddTextEntry("COMPONENT_glock18c_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_glock18c_CLIP_02", "Drum Magazine")
    AddTextEntry("COMPONENT_MP5SD_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_MP5SD_CLIP_02", "Drum Magazine")
    AddTextEntry("COMPONENT_M16_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_MP9_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_MP9_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_SigSauerMPX_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_SigSauerMPX_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_STG_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_STG_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_MP40_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_MP40_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_M4A1_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_L85A2_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_FNL1A1_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_G36C_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_AK74_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_AK47_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_AK47_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_BIZON_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_BIZON_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_luger_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_luger_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_MP5A5_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_MP5A5_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_Saiga12_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_Saiga12_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_FN502_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_ACR_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_ACR_CLIP_02", "Extended Clip")
    AddTextEntry("COMPONENT_ACR_CLIP_ap", "URGI Clip")
    AddTextEntry("COMPONENT_VIETNAM_CLIP_01", "20 Round Magazine")
    AddTextEntry("COMPONENT_COMP_CLIP_01", "10 Round Magazine")
    AddTextEntry("COMPONENT_COMP_CLIP_02", "10 Round Military Marked Magazine")
    AddTextEntry("COMPONENT_OMEGA_CLIP_01", "Beta-C style Drum Mag")
    AddTextEntry("COMPONENT_MILITARY_CLIP_01", "30 Mound Military Marked Magazine")
    AddTextEntry("COMPONENT_MILITARY_CLIP_02", "40 Round Military Marked Magazine")
    AddTextEntry("COMPONENT_CAR15_CLIP_01", "Default Clip")
    AddTextEntry("COMPONENT_CAR15_CLIP_02", "20 Round Magazine")
    AddTextEntry("COMPONENT_M4A1FM_CLIP_01", "STANAG 5.56 Mag")
    AddTextEntry("COMPONENT_M4A1FM_CLIP_02", "Magpul PMAG")
    AddTextEntry("COMPONENT_M4A1FM_CLIP_03", "Surefire Quadstack")
    AddTextEntry("COMPONENT_M4A1FM_CLIP_04", "X15 Drum")
    AddTextEntry("COMPONENT_MDR_CLIP_01", "STANAG 5.56 Magazine")
    AddTextEntry("COMPONENT_MDR_CLIP_02", "STANAG 5.56 Magazine 2")
    AddTextEntry("COMPONENT_MDR_CLIP_03", "5.56 X15 Drum")
    AddTextEntry("COMPONENT_MDR_CLIP_04", "Magpul PMAG")
    AddTextEntry("COMPONENT_MDR_CLIP_05", "Magpul PMAG 2")
    AddTextEntry("COMPONENT_MDR_CLIP_06", "Magpul PMAG Extended")
    AddTextEntry("COMPONENT_MDR_CLIP_07", "Magpul PMAG Extended 2")
    AddTextEntry("COMPONENT_MDR_CLIP_08", "Surefire 5.56 Quadstack")
    AddTextEntry("COMPONENT_MDR_CLIP_09", "Surefire 5.56 Extended Quadstack")
    AddTextEntry("COMPONENT_MDR2_CLIP_01", "Standard STANAG 7.62 NATO")
    AddTextEntry("COMPONENT_MDR2_CLIP_02", "Magpul 7.62 NATO PMAG")
    AddTextEntry("COMPONENT_MDR2_CLIP_03", "Alt 7.62 NATO Straight Mag")
    AddTextEntry("COMPONENT_MDR2_CLIP_04", "7.62 NATO Stendo")
    AddTextEntry("COMPONENT_MDR2_CLIP_05", "Polymer 7.62 NATO Stendo")
    AddTextEntry("COMPONENT_MDR2_CLIP_06", "Extended 7.62 NATO Mag")
    AddTextEntry("COMPONENT_MDR2_CLIP_07", "Polymer Heavy Drum")

    -- Scopes

    AddTextEntry("COMPONENT_IRON_SIGHT_02", "Iron sight")
    AddTextEntry("COMPONENT_AT_SCOPE_MP9", "Scope")
    AddTextEntry("COMPONENT_M4A1FM_SCOPE_01", "M4A1 Standard Carry Handle")
    AddTextEntry("COMPONENT_M4A1FM_SCOPE_02", "Trijicon ACOG on Carry Handle")
    AddTextEntry("COMPONENT_M4A1FM_SCOPE_03", "Eotech EXPS-1")
    AddTextEntry("COMPONENT_M4A1FM_SCOPE_04", "Eotech 552")
    AddTextEntry("COMPONENT_MDR_SCOPE_01", "Magpul Flip Up Sights")
    AddTextEntry("COMPONENT_MDR_SCOPE_02", "Walther MRS Reflex")
    AddTextEntry("COMPONENT_MDR_SCOPE_03", "Aimpoint Micro T1")
    AddTextEntry("COMPONENT_MDR_SCOPE_04", "Eotech 552")
    AddTextEntry("COMPONENT_MDR2_SCOPE_01", "Magpul Folding Sights")
    AddTextEntry("COMPONENT_MDR2_SCOPE_02", "Walther MRS Reflex Sight")
    AddTextEntry("COMPONENT_MDR2_SCOPE_03", "Aimpoint Micro T1 Sight")
    AddTextEntry("COMPONENT_MDR2_SCOPE_04", "Aimpoint Red Dot")
    AddTextEntry("COMPONENT_MDR2_SCOPE_05", "SIG Bravo")
    AddTextEntry("COMPONENT_MDR2_SCOPE_06", "Trijicon ACOG Optic")

    -- Stocks

    AddTextEntry("COMPONENT_AT_PRC_STOCK_COLLAPSED", "Stock collapsed")  


    -- Pistol Grip



    -- Handguard



    -- Grips
    AddTextEntry("COMPONENT_MDR_GRIP", "Magpul AFG")
    AddTextEntry("COMPONENT_MDR2_GRIP_01", "Magpul AFG Grip")
    AddTextEntry("COMPONENT_MDR2_GRIP_02", "Magpul AFG Grip Alt")
    AddTextEntry("COMPONENT_MDR2_GRIP_03", "Magpul AFG Grip Alt 2")

    -- Dust Cover



    -- Muzzle

    AddTextEntry("COMPONENT_AT_MUZZLE_BRD", "Birdcage style muzzle")

    -- Flashlight

    AddTextEntry("COMPONENT_CAR15_AR_FLSH", "Flashlight")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_01", "L3Harris ATPIAL Black")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_02", "L3Harris ATPIAL Tan")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_03", "L3Harris ATPIAL Black 2")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_04", "L3Harris ATPIAL Tan 2")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_05", "Zenitco Perst-3")
    AddTextEntry("COMPONENT_M4A1FM_FLSH_06", "Surefire X300 Ultra LED")
    AddTextEntry("COMPONENT_MDR2_FLSH_01", "Steiner Optics DBAL")
    AddTextEntry("COMPONENT_MDR2_FLSH_02", "ANPEQ-15 Module")
    AddTextEntry("COMPONENT_MDR2_FLSH_03", "ANPEQ-15 Module Alt")
    AddTextEntry("COMPONENT_MDR2_FLSH_04", "Laser Pointer")
    AddTextEntry("COMPONENT_MDR2_FLSH_05", "Surefire X300 Flashlight")
    AddTextEntry("COMPONENT_MDR2_FLSH_06", "Pistol Flashlight")

    -- Suppressor

    AddTextEntry("COMPONENT_AT_FN502_SUPP", "Suppressor")
    AddTextEntry("COMPONENT_AT_MP9_SUPP_02", "Suppressor")
    AddTextEntry("COMPONENT_M4A1FM_BARREL_01", "Standard M4 Barrel")
    AddTextEntry("COMPONENT_M4A1FM_BARREL_02", "Rifle Length M4 Barrel")
    AddTextEntry("COMPONENT_M4A1FM_BARREL_03", "Standard Suppressed Barrel")
    AddTextEntry("COMPONENT_M4A1FM_BARREL_04", "Rifle Length Suppressed Barrel")
    AddTextEntry("COMPONENT_MDR_SUPP_01", "KAC Suppressor")
    AddTextEntry("COMPONENT_MDR_SUPP_02", "KAC Suppressor Alt")
    AddTextEntry("COMPONENT_MDR_SUPP_03", "Custom Suppressor")
    AddTextEntry("COMPONENT_MDR_SUPP_04", "SOCOM Suppressor")
    AddTextEntry("COMPONENT_MDR_SUPP_05", "SOCOM Suppressor Alt")
    AddTextEntry("COMPONENT_MDR2_SUPP_01", "MDR Tube Suppressor")
    AddTextEntry("COMPONENT_MDR2_SUPP_02", "KAC 7.62 Long Can")
    AddTextEntry("COMPONENT_MDR2_SUPP_03", "7.62 NATO Short Can")

    -- Skins

    AddTextEntry("COMPONENT_GLOCK18C_VARMOD_Liv1", "Demon Time Skin")
end)