--Streetnames/area names script

Citizen.CreateThread(function()
    AddTextEntry("roxsquid", "Squidrillo Fwy")
    AddTextEntry("roxclam", "Clam Way")
    AddTextEntry("roxorteg", "Ortega Dr")
    AddTextEntry("roxparto", "Del Parto Canal St")
    AddTextEntry("roxrivav", "Riverfront Ave")
    AddTextEntry("roxdolph", "Dolphin Dr")
    AddTextEntry("roxsunln", "Sunrise Ln")
    AddTextEntry("roxpearl", "Pearl Rd")
    AddTextEntry("roxconny", "Conny Ln")
    AddTextEntry("roxshell", "Shell Bead Rd")
    AddTextEntry("roxbaydr", "Bayview Dr")
    AddTextEntry("roxvoya", "Great Voyage Rd")
    AddTextEntry("roxbaybr", "Bayview Bridge")
    AddTextEntry("roxwood", "Roxwood")
    AddTextEntry("roxmarb", "Marina Beach")
    AddTextEntry("roxdock", "Marina Docks")
end)