local weapons = {
	'WEAPON_DAGGER',
	'WEAPON_BAT',
	'WEAPON_BOTTLE',
	'WEAPON_CROWBAR',
	'WEAPON_UNARMED',
	'WEAPON_FLASHLIGHT',
	'WEAPON_GOLFCLUB',
	'WEAPON_HAMMER',
	'WEAPON_HATCHET',
	'WEAPON_KNUCKLE',
	'WEAPON_KNIFE',
	'WEAPON_MACHETE',
	'WEAPON_SWITCHBLADE',
	'WEAPON_NIGHTSTICK',
	'WEAPON_WRENCH',
	'WEAPON_BATTLEAXE',
	'WEAPON_POOLCUE',
	'WEAPON_STONE_HATCHET',
	'WEAPON_PISTOL',
	'WEAPON_PISTOL_MK2',
	'WEAPON_COMBATPISTOL',
	'WEAPON_APPISTOL',
	'WEAPON_STUNGUN',
	'WEAPON_PISTOL50',
	'WEAPON_SNSPISTOL',
	'WEAPON_SNSPISTOL_MK2',
	'WEAPON_HEAVYPISTOL',
	'WEAPON_VINTAGEPISTOL',
	'WEAPON_FLAREGUN',
	'WEAPON_MARKSMANPISTOL',
	'WEAPON_REVOLVER',
	'WEAPON_REVOLVER_MK2',
	'WEAPON_DOUBLEACTION',
	'WEAPON_RAYPISTOL',
	'WEAPON_CERAMICPISTOL',
	'WEAPON_NAVYREVOLVER',
	'WEAPON_GADGETPISTOL',
	'WEAPON_STUNGUN_MP',
	'WEAPON_MICROSMG',
	'WEAPON_SMG',
	'WEAPON_SMG_MK2',
	'WEAPON_ASSAULTSMG',
	'WEAPON_COMBATPDW',
	'WEAPON_MACHINEPISTOL',
	'WEAPON_MINISMG',
	'WEAPON_RAYCARBINE',
	'WEAPON_PUMPSHOTGUN',
	'WEAPON_PUMPSHOTGUN_MK2',
	'WEAPON_SAWNOFFSHOTGUN',
	'WEAPON_ASSAULTSHOTGUN',
	'WEAPON_BULLPUPSHOTGUN',
	'WEAPON_MUSKET',
	'WEAPON_HEAVYSHOTGUN',
	'WEAPON_DBSHOTGUN',
	'WEAPON_AUTOSHOTGUN',
	'WEAPON_COMBATSHOTGUN',
	'WEAPON_ASSAULTRIFLE',
	'WEAPON_ASSAULTRIFLE_MK2',
	'WEAPON_CARBINERIFLE',
	'WEAPON_CARBINERIFLE_MK2',
	'WEAPON_ADVANCEDRIFLE',
	'WEAPON_SPECIALCARBINE',
	'WEAPON_SPECIALCARBINE_MK2',
	'WEAPON_BULLPUPRIFLE',
	'WEAPON_BULLPUPRIFLE_MK2',
	'WEAPON_COMPACTRIFLE',
	'WEAPON_MILITARYRIFLE',
	'WEAPON_TACTICALRIFLE',
	"WEAPON_HEAVYRIFLE",
	'WEAPON_MG',
	'WEAPON_COMBATMG',
	'WEAPON_COMBATMG_MK2',
	'WEAPON_GUSENBERG',
	'WEAPON_SNIPERRIFLE',
	'WEAPON_HEAVYSNIPER',
	'WEAPON_HEAVYSNIPER_MK2',
	'WEAPON_MARKSMANRIFLE',
	'WEAPON_MARKSMANRIFLE_MK2',
	"WEAPON_CV_PRECISIONRIFLE",
	'WEAPON_RPG',
	'WEAPON_GRENADELAUNCHER',
	'WEAPON_GRENADELAUNCHER_SMOKE',
	'WEAPON_MINIGUN',
	'WEAPON_FIREWORK',
	'WEAPON_RAILGUN',
	'WEAPON_HOMINGLAUNCHER',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_RAYMINIGUN',
	'WEAPON_GRENADE',
	'WEAPON_BZGAS',
	'WEAPON_MOLOTOV',
	'WEAPON_STICKYBOMB',
	'WEAPON_PROXMINE',
	'WEAPON_SNOWBALL',
	'WEAPON_PIPEBOMB',
	'WEAPON_BALL',
	'WEAPON_SMOKEGRENADE',
	'WEAPON_FLARE',
	'WEAPON_PETROLCAN',
	'WEAPON_FIREEXTINGUISHER',
	'WEAPON_HAZARDCAN',
	'WEAPON_EMPLAUNCHER',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_VECTOR',
}

weaponClasses = {
	["pistol"] = {
		'WEAPON_PISTOL',
		'WEAPON_PISTOL_MK2',
		'WEAPON_COMBATPISTOL',
		'WEAPON_APPISTOL',
		'WEAPON_STUNGUN',
		'WEAPON_PISTOL50',
		'WEAPON_SNSPISTOL',
		'WEAPON_SNSPISTOL_MK2',
		'WEAPON_HEAVYPISTOL',
		'WEAPON_VINTAGEPISTOL',
		'WEAPON_FLAREGUN',
		'WEAPON_MARKSMANPISTOL',
		'WEAPON_REVOLVER',
		'WEAPON_REVOLVER_MK2',
		'WEAPON_DOUBLEACTION',
		'WEAPON_RAYPISTOL',
		'WEAPON_CERAMICPISTOL',
		'WEAPON_NAVYREVOLVER',
		'WEAPON_GADGETPISTOL',
		'WEAPON_STUNGUN_MP',
	},
	["shotgun"] = {
		'WEAPON_HEAVYSHOTGUN',
		'WEAPON_DBSHOTGUN',
		'WEAPON_AUTOSHOTGUN',
		'WEAPON_COMBATSHOTGUN',
		'WEAPON_PUMPSHOTGUN',
		'WEAPON_PUMPSHOTGUN_MK2',
		'WEAPON_SAWNOFFSHOTGUN',
		'WEAPON_ASSAULTSHOTGUN',
		'WEAPON_BULLPUPSHOTGUN',
	},
	["ar"] = {
		'WEAPON_MILITARYRIFLE',
		'WEAPON_ASSAULTRIFLE',
		'WEAPON_ASSAULTRIFLE_MK2',
		'WEAPON_CARBINERIFLE',
		'WEAPON_CARBINERIFLE_MK2',
		'WEAPON_ADVANCEDRIFLE',
		'WEAPON_SPECIALCARBINE',
		'WEAPON_SPECIALCARBINE_MK2',
		'WEAPON_BULLPUPRIFLE',
		'WEAPON_BULLPUPRIFLE_MK2',
		'WEAPON_RAYCARBINE',
		"WEAPON_TACTICALRIFLE",
		"WEAPON_HEAVYRIFLE",
	},
	["lmg"] = {
		'WEAPON_MG',
		'WEAPON_COMBATMG',
		'WEAPON_COMBATMG_MK2',
	},
	["smg"] = {
		'WEAPON_MICROSMG',
		'WEAPON_SMG',
		'WEAPON_SMG_MK2',
		'WEAPON_GUSENBERG',
		'WEAPON_COMPACTRIFLE',
		'WEAPON_ASSAULTSMG',
		'WEAPON_COMBATPDW',
		'WEAPON_MINISMG',
		'WEAPON_MACHINEPISTOL',
		'WEAPON_VECTOR',
	},
	["explosive"] = {
		'WEAPON_PIPEBOMB',
		'WEAPON_STICKYBOMB',
		'WEAPON_GRENADE',
		'WEAPON_RAILGUN',
		'WEAPON_HOMINGLAUNCHER',
		'WEAPON_COMPACTLAUNCHER',
		'WEAPON_RAYMINIGUN',
		'WEAPON_RPG',
		'WEAPON_GRENADELAUNCHER',
		"WEAPON_COMPACTLAUNCHER",
		"WEAPON_EMPLAUNCHER",
	},
	["sniper"] = {
		'WEAPON_SNIPERRIFLE',
		'WEAPON_HEAVYSNIPER',
		'WEAPON_HEAVYSNIPER_MK2',
		'WEAPON_MARKSMANRIFLE',
		'WEAPON_MARKSMANRIFLE_MK2',
		'WEAPON_MUSKET',
		"WEAPON_CV_PRECISIONRIFLE",
	},
	["special"] = {
		'WEAPON_BALL',
		'WEAPON_SMOKEGRENADE',
		'WEAPON_FLARE',
		'WEAPON_PETROLCAN',
		'WEAPON_FIREEXTINGUISHER',
		'WEAPON_HAZARDCAN',
		'WEAPON_MOLOTOV',
		'WEAPON_BZGAS',
		'WEAPON_MINIGUN',
		'WEAPON_GRENADELAUNCHER_SMOKE',
	},
	["melee"] = {
		'WEAPON_DAGGER',
		'WEAPON_BAT',
		'WEAPON_BOTTLE',
		'WEAPON_CROWBAR',
		'WEAPON_UNARMED',
		'WEAPON_FLASHLIGHT',
		'WEAPON_GOLFCLUB',
		'WEAPON_HAMMER',
		'WEAPON_HATCHET',
		'WEAPON_KNUCKLE',
		'WEAPON_KNIFE',
		'WEAPON_MACHETE',
		'WEAPON_SWITCHBLADE',
		'WEAPON_NIGHTSTICK',
		'WEAPON_WRENCH',
		'WEAPON_BATTLEAXE',
		'WEAPON_POOLCUE',
		'WEAPON_STONE_HATCHET',
	}
}

weaponNames = {
    [`weapon_advancedrifle`] = 'Advanced Rifle',
    [`weapon_appistol`] = 'AP Pistol',
    [`weapon_assaultrifle`] = 'Assault Rifle',
    [`weapon_assaultrifle_mk2`] = 'Assault Rifle Mk II',
    [`weapon_assaultshotgun`] = 'Assault Shotgun',
    [`weapon_assaultsmg`] = 'Assault SMG',
    [`weapon_autoshotgun`] = 'Sweeper Shotgun',
    [`weapon_bat`] = 'Baseball Bat',
    [`weapon_ball`] = 'Ball',
    [`weapon_battleaxe`] = 'Battle Axe',
    [`weapon_bottle`] = 'Bottle',
    [`weapon_bullpuprifle`] = 'Bullpup Rifle',
    [`weapon_bullpuprifle_mk2`] = 'Bullpup Rifle Mk II',
    [`weapon_bullpupshotgun`] = 'Bullpup Shotgun',
    [`weapon_bzgas`] = 'BZ Gas',
    [`weapon_carbinerifle`] = 'Carbine Rifle',
    [`weapon_carbinerifle_mk2`] = 'Carbine Rifle Mk II',
    [`weapon_combatmg`] = 'Combat MG',
    [`weapon_combatmg_mk2`] = 'Combat MG Mk II',
    [`weapon_combatpdw`] = 'Combat PDW',
    [`weapon_combatpistol`] = 'Combat Pistol',
    [`weapon_compactlauncher`] = 'Compact Grenade Launcher',
    [`weapon_compactrifle`] = 'Compact Rifle',
    [`weapon_crowbar`] = 'Crowbar',
    [`weapon_dagger`] = 'Antique Cavalry Dagger',
    [`weapon_dbshotgun`] = 'Double Barrel Shotgun',
    [`weapon_doubleaction`] = 'Double-Action Revolver',
    [`weapon_fireextinguisher`] = 'Fire Extinguisher',
    [`weapon_firework`] = 'Firework Launcher',
    [`weapon_flare`] = 'Flare',
    [`weapon_flaregun`] = 'Flare Gun',
    [`weapon_flashlight`] = 'Flashlight',
    [`weapon_golfclub`] = 'Golf Club',
    [`weapon_grenade`] = 'Grenade',
    [`weapon_grenadelauncher`] = 'Grenade Launcher',
    [`weapon_gusenberg`] = 'Gusenberg Sweeper',
    [`weapon_hammer`] = 'Hammer',
    [`weapon_hatchet`] = 'Hatchet',
    [`weapon_heavypistol`] = 'Heavy Pistol',
    [`weapon_heavyshotgun`] = 'Heavy Shotgun',
    [`weapon_heavysniper`] = 'Heavy Sniper',
    [`weapon_heavysniper_mk2`] = 'Heavy Sniper Mk II',
    [`weapon_hominglauncher`] = 'Homing Launcher',
    [`weapon_knife`] = 'Knife',
    [`weapon_knuckle`] = 'Knuckle Duster',
    [`weapon_machete`] = 'Machete',
    [`weapon_machinepistol`] = 'Machine Pistol',
    [`weapon_marksmanpistol`] = 'Marksman Pistol',
    [`weapon_marksmanrifle`] = 'Marksman Rifle',
    [`weapon_marksmanrifle_mk2`] = 'Marksman Rifle Mk II',
    [`weapon_mg`] = 'MG',
    [`weapon_microsmg`] = 'Micro SMG',
    [`weapon_minigun`] = 'Minigun',
    [`weapon_minismg`] = 'Mini SMG',
    [`weapon_molotov`] = 'Molotov',
    [`weapon_musket`] = 'Musket',
    [`weapon_nightstick`] = 'Nightstick',
    [`weapon_petrolcan`] = 'Jerry Can',
    [`weapon_pipebomb`] = 'Pipe Bomb',
    [`weapon_pistol`] = 'Pistol',
    [`weapon_pistol50`] = 'Pistol .50',
    [`weapon_pistol_mk2`] = 'Pistol Mk II',
    [`weapon_poolcue`] = 'Pool Cue',
    [`weapon_proxmine`] = 'Proximity Mine',
    [`weapon_pumpshotgun`] = 'Pump Shotgun',
    [`weapon_pumpshotgun_mk2`] = 'Pump Shotgun Mk II',
    [`weapon_railgun`] = 'Railgun',
    [`weapon_revolver`] = 'Heavy Revolver',
    [`weapon_revolver_mk2`] = 'Heavy Revolver Mk II',
    [`weapon_rpg`] = 'RPG',
    [`weapon_sawnoffshotgun`] = 'Sawed-Off Shotgun',
    [`weapon_smg`] = 'SMG',
    [`weapon_smg_mk2`] = 'SMG Mk II',
    [`weapon_smokegrenade`] = 'Tear Gas',
    [`weapon_sniperrifle`] = 'Sniper Rifle',
    [`weapon_snowball`] = 'Snowball',
    [`weapon_snspistol`] = 'SNS Pistol',
    [`weapon_snspistol_mk2`] = 'SNS Pistol Mk II',
    [`weapon_specialcarbine`] = 'Special Carbine',
    [`weapon_specialcarbine_mk2`] = 'Special Carbine Mk II',
    [`weapon_stickybomb`] = 'Sticky Bomb',
    [`weapon_stungun`] = 'Stun Gun',
    [`weapon_switchblade`] = 'Switchblade',
    [`weapon_vintagepistol`] = 'Vintage Pistol',
    [`weapon_wrench`] = 'Pipe Wrench',
    [`weapon_raypistol`] = 'Up-n-Atomizer',
    [`weapon_raycarbine`] = 'Unholy Hellbringer',
    [`weapon_rayminigun`] = 'Widowmaker',
    [`weapon_stone_hatchet`] = 'Stone Hatchet',
	[`weapon_cv_precisionrifle`] = 'Precision Rifle',
	[`weapon_militaryrifle`] = 'Military Rifle',
	[`weapon_tacticalrifle`] = 'Service Rifle',
	[`weapon_heavyrifle`] = 'Heavy Rifle',
	[`weapon_combatshotgun`] = 'Combat Shotgun',
	[`weapon_unarmed`] = 'Fists',
	[`weapon_emplauncher`] = 'EMP Launcher',
	[`weapon_vector`] = 'Kriss Vector'
}

weaponHashes = {}
for _,v in pairs(weapons) do
	weaponHashes[GetHashKey(v)] = v
end


weaponClassByName = {}
for class, v in pairs(weaponClasses) do
	for _, weapon in pairs(v) do
		weaponClassByName[weapon] = class
	end
end