Citizen.CreateThread(function()
    -- Engine Audios Ported from v1
    AddTextEntry("4age", "Futo Custom")
    AddTextEntry("918spyeng", "Pfister SR")
    AddTextEntry("alfa690t", "Felon SC")
    AddTextEntry("aventadorv12", "Zentorno V12")
    AddTextEntry("b58b30", "Cypher Tuned")
    AddTextEntry("bmws1krreng", "Bati 801 Tuned")
    AddTextEntry("bmws702", "Oracle 2V8")
    AddTextEntry("c30a", "Chavos 4")
    AddTextEntry("camls3v8", "Vigeroo")
    AddTextEntry("chevroletlt4", "Coquette V8")
    AddTextEntry("demonv8", "STX V8")
    AddTextEntry("dlc2015mustsound", "Hellenbach 15")
    AddTextEntry("f136", "Furore GT2")
    AddTextEntry("fdvsffeng", "ZR250 Tuned")
    AddTextEntry("fordvoodoo", "Voodoo 2")
    AddTextEntry("gallardov10", "vaccav10")
    AddTextEntry("gt3rstun", "CometS2 V8")
    AddTextEntry("hondaf20c", "Chavos Tuned")
    AddTextEntry("huracanv10", "Tempesta V10")
    AddTextEntry("ktm1290r", "Esskey V2")
    AddTextEntry("lamavgineng", "Infernus v12")
    AddTextEntry("lfasound", "ETR V6")
    AddTextEntry("mercm177", "Shafter V8")
    AddTextEntry("ml720v8eng", "Emerus V2")
    AddTextEntry("nfsv8", "Domin V8")
    AddTextEntry("nisgtr35", "RH8 V6")
    AddTextEntry("nsr2teng", "Roxanne l6")
    AddTextEntry("pgzonreng", "Osiris V12")
    AddTextEntry("r34sound", "Euros Custom")
    AddTextEntry("r35sound", "Elegy V8")
    AddTextEntry("rb26dett", "Elegy Retro V2")
    AddTextEntry("rotary7", "Savestrar 4r")
    AddTextEntry("s63b44", "Oracle V8")
    AddTextEntry("s85b50", "Rebla Custom")
    AddTextEntry("audiea839", "Kuruma 2")
    AddTextEntry("suzukigsxr1k", "PCJ6001")
    AddTextEntry("ta011mit4g63", "Citi2")
    AddTextEntry("tjz1eng", "Previon V6")
    AddTextEntry("toysupmk4", "PrevionV6 TwinT")
    AddTextEntry("z33dkffeng", "ZR380 Classic")
    AddTextEntry("z33u2", "ZR380 Classic v2")
    AddTextEntry("subaruej20", "Kuruma 20")

end)