Citizen.CreateThread(function()
-- December 2023 Update 1
AddTextEntry("elegyrh4", "Annis Elegy RH4")
AddTextEntry("elegydm", "Annis Elegy RH5 Drift Missile")
AddTextEntry("elegyheritage", "Annis Elegy RH5 Heritage Edition")
AddTextEntry("elegyrace", "Annis Elegy RH5 Heritage Racer")
AddTextEntry("elegyp", "Annis Elegy RH5 Police Interceptor")
AddTextEntry("elegyrh7", "Annis Elegy RH7")
AddTextEntry("elegyrh72", "Annis Elegy RH7 Alt Spec")
AddTextEntry("rh8fr", "Annis Elegy RH8 FR Works")
AddTextEntry("rh8mandem", "Annis Elegy RH8 Mandem")
AddTextEntry("elegyx", "Annis Elegy RH8X")
AddTextEntry("kawaii", "Annis Kawaii")
AddTextEntry("majimagt", "Annis Majima GT Road Car")
AddTextEntry("majimalm", "Annis Majima Le Mans")
AddTextEntry("remusvert", "Annis Remus Convertible")
AddTextEntry("roxanne", "Annis Roxanne")
AddTextEntry("s230", "Annis S230")
AddTextEntry("trailwinder", "Annis Trailwinder")
AddTextEntry("zr150", "Annis ZR150 Savestra")
AddTextEntry("zr250", "Annis ZR250 Savestra")
AddTextEntry("zr", "Annis ZR350 Alt Spec")
AddTextEntry("zrgpr", "Annis ZR350 ReMaul Custom")
AddTextEntry("zr380s", "Annis ZR380 Base Spec")
AddTextEntry("zr380c", "Annis ZR380 Widebody")
AddTextEntry("zr390", "Annis ZR390")
AddTextEntry("clubgtr", "BF Club GTR")
AddTextEntry("clubta", "BF Racing Club")
AddTextEntry("schlagenstr", "Benefactor Schlagen STR")
AddTextEntry("spritzer", "Benefactor Spritzer STR")
AddTextEntry("buffalot", "Bravado Buffalo S Widebody")
AddTextEntry("vulture", "Bravado Vulture")
AddTextEntry("picadorexr", "Cheval Picador EXR")
AddTextEntry("tampax2", "Declasse Tampa WildbodyX")
AddTextEntry("tulipss", "Declasse Tulip SS")
AddTextEntry("supergts", "Dewbauchee Super GTS")
AddTextEntry("frakas", "Dinka Frakas")
AddTextEntry("jester5", "Dinka Jester Northwind Spec")
AddTextEntry("nexus", "Dinka Nexus")
AddTextEntry("serena", "Dinka Serena")
AddTextEntry("revolver", "Dundreary Regina Revolver")
AddTextEntry("altior", "Emperor Altior")
AddTextEntry("es550", "Emperor ES550")
AddTextEntry("sheavas", "Emperor Sheava")
AddTextEntry("deimos", "Grotti Deimos GTS")
AddTextEntry("italigtc", "Grotti Itali GTC")
AddTextEntry("italigtr", "Grotti Itali GTR")
AddTextEntry("italigts", "Grotti Itali GTS")
AddTextEntry("gtcslm", "Grotti Turismo Classic LM Spyder")
AddTextEntry("turismoc", "Grotti Turismo Classic Widebody")
AddTextEntry("vertice", "Hijak Vertice")
AddTextEntry("deluxogt", "Imponte Deluxo GT")
AddTextEntry("deluxo2", "Imponte Deluxo V6")
AddTextEntry("firecast", "Imponte Firecast Ruiner")
AddTextEntry("ariant", "Karin Ariant")
AddTextEntry("asters", "Karin Asterope RS 2010")
AddTextEntry("boorc", "Karin Boor Widebody")
AddTextEntry("dilettandedx", "Karin Dilettante DX")
AddTextEntry("everonbase", "Karin Everon Base Spec")
AddTextEntry("futo6str", "Karin Futo GT Hatch 6STR Edition")
AddTextEntry("n2futo", "Karin Futo GT Hatch N2 Spec")
AddTextEntry("rebeld", "Karin Rebel Drift Spec")
AddTextEntry("sigma3", "Karin SigmaThree")
AddTextEntry("sigma2", "Karin SigmaTwo")
AddTextEntry("sultanbase", "Karin Sultan Classic Base Spec")
AddTextEntry("sultanv8", "Karin Sultan RS V8 Swap")
AddTextEntry("tubular", "Karin Sultan Tubular")
AddTextEntry("sultanw", "Karin Sultan Wagon")
AddTextEntry("komodafr", "Lampadati Komoda FR Works")
AddTextEntry("mosquito", "Maibatsu Mosquito")
AddTextEntry("revolutions", "Maibatsu Revolution")
AddTextEntry("revolutionw", "Maibatsu Revolution 6STR Widebody")
AddTextEntry("sunrise1", "Maibatsu Sunrise R")
AddTextEntry("vincent2", "Maibatsu Vincent")
AddTextEntry("vincent3", "Maibatsu Vincent Wagon")
AddTextEntry("nkart", "Nagasaki Kart")
AddTextEntry("kunoisa", "Nagasaki Kunoichi")
AddTextEntry("shopkart", "Nagasaki ShoppingKart")
AddTextEntry("doubled", "Obey 3F DD")
AddTextEntry("bati701", "Pegassi Bati 701")
AddTextEntry("bati901", "Pegassi Bati 901")
AddTextEntry("infernussr", "Pegassi Infernus S Roadster")
AddTextEntry("infernus2se", "Pegassi Infernus SE Classic")
AddTextEntry("osirisfr", "Pegassi Osiris FR Works")
AddTextEntry("osirisr", "Pegassi Osiris R")
AddTextEntry("severo", "Pegassi Severo")
AddTextEntry("tempesta2", "Pegassi Tempesta 6STR Edition")
AddTextEntry("tempestaes", "Pegassi Tempesta Evo Stradale")
AddTextEntry("tempestafr", "Pegassi Tempesta FR Works")
AddTextEntry("tempestas", "Pegassi Tempesta Spyder")
AddTextEntry("torerod", "Pegassi Torero Classic YDrop Edition")
AddTextEntry("vaccamw", "Pegassi Vacca Escapist Edition")
AddTextEntry("apollo", "Pfister Apollo")
AddTextEntry("callista", "Pfister Comet Callista")
AddTextEntry("cometrwt", "Pfister Comet RWT 6STR")
AddTextEntry("meteor", "Pfister Meteor")
AddTextEntry("castella", "Shitzu Castella")
AddTextEntry("castellajp", "Shitzu Castella Police Cruiser")
AddTextEntry("vtf650", "Shitzu VTF650")
AddTextEntry("kampfer", "Ubermacht Kampfer")
AddTextEntry("ziongtc", "Ubermacht Zion GTC")
AddTextEntry("bulletgt", "Vapid Bullet GT")
AddTextEntry("hachura", "Vulcar Hachura R")
AddTextEntry("hachurac", "Vulcar Hachura R Custom")

-- January 2024 Update 1

AddTextEntry("turismowb", "2008 Grotti Turismo Widebody Custom")
AddTextEntry("elegyute", "Annis Elegy RH5 UTE")
AddTextEntry("as_nexus", "Annis Nexus Nishukan")
AddTextEntry("requiemzr1", "Annis Requiem ZR")
AddTextEntry("as", "Annis ZR350 Nishukan")
AddTextEntry("furzen", "BF Furzen")
AddTextEntry("scheisser", "Benefactor Scheisser")
AddTextEntry("bansheepo", "Bravado Banshee Phase One")
AddTextEntry("polbisonr", "Bravado Bison BCOS")
AddTextEntry("buffalo4h", "Bravado Buffalo Hellfire")
AddTextEntry("polbuffalor", "Bravado Buffalo S BCOS")
AddTextEntry("polbuffalor2", "Bravado Buffalo SX BCOS")
AddTextEntry("buffalosxf", "Bravado Buffalo SX LSFD")
AddTextEntry("polgauntletr", "Bravado Gaunlet SX BCOS")
AddTextEntry("gauntlets", "Bravado Gauntlet S Concept")
AddTextEntry("gauntletstx", "Bravado Gauntlet STX")
AddTextEntry("polgresleyr", "Bravado Gresley BCOS")
AddTextEntry("verlierergt", "Bravado Verlierer GT")
AddTextEntry("polalamor", "Declasse Alamo BCOS")
AddTextEntry("polalamor2", "Declasse Alamo BCOS Alt Spec")
AddTextEntry("aseac", "Declasse Asea Custom")
AddTextEntry("h4rxgranut", "Declasse Granger 3600UT")
AddTextEntry("sabrec", "Declasse Sabre Deluxe")
AddTextEntry("tulip4", "Declasse Tulip M100 Stock")
AddTextEntry("vigerogt", "Declasse Vigero GT")
AddTextEntry("jdvigeror", "Declasse Vigero Rumbler")
AddTextEntry("jdvigerord", "Declasse Vigero Rumbler Drag")
AddTextEntry("vigeronew", "Declasse Vigero VL1 690SS")
AddTextEntry("polvigeror", "Declasse Vigero ZX BCOS")
AddTextEntry("jefferson", "Dundreary Jefferson")
AddTextEntry("polroamerr", "Dundreary Landstalker BCOS")
AddTextEntry("polstalkerr", "Dundreary Landstalker XL BCOS")
AddTextEntry("baller8", "Gallivanter Baller LE Cruiser")
AddTextEntry("bestiagt", "Grotti Bestia GT")
AddTextEntry("citrus", "Iemanjá Citrus")
AddTextEntry("polcoquetter", "Invetero Coquette BCOS")
AddTextEntry("coquette4c", "Invetero Coquette D10 Custom")
AddTextEntry("coqvice", "Invetero Coquette Vice")
AddTextEntry("coqvice2", "Invetero Coquette Vice Cabrio")
AddTextEntry("thunderstruck", "Invetero Thunderstruck Coquette")
AddTextEntry("sultan2c", "Karin Sultan Classic Custom")
AddTextEntry("mesos", "Lampadati Mesos Rallye")
AddTextEntry("shinobio", "Nagasaki Shinobi Outlaw")
AddTextEntry("shinobir", "Nagasaki Shinobi R")
AddTextEntry("estancia", "Ocelot Estancia")
AddTextEntry("f620s", "Ocelot F620 V12")
AddTextEntry("f620s2", "Ocelot F620 V12 Sleeper")
AddTextEntry("tempestar", "Pegassi Tempesta R")
AddTextEntry("ares", "Progen Ares")
AddTextEntry("cwagon", "Schyster Compact Wagon")
AddTextEntry("fusiladev8", "Schyster Fusilade V8")
AddTextEntry("cyphct", "Ubermacht Cypher Hatchback")
AddTextEntry("sentinel6str2", "Ubermacht Sentinel 6STR Custom")
AddTextEntry("sentineldtm", "Ubermacht Sentinel Classic DTM Spec")
AddTextEntry("sentinelc", "Ubermacht Sentinel Widebody Custom")
AddTextEntry("sentigpr", "Ubermacht Sentinel XR")
AddTextEntry("sentinelxs", "Ubermacht Sentinel XS Refined Edition")
AddTextEntry("vorstand", "Ubermacht Vorstand")
AddTextEntry("zionks", "Ubermacht Zion Krieger Specials")
AddTextEntry("zionv10", "Ubermacht Zion V10")
AddTextEntry("bcatctx", "Vapid Bobcat CTX")
AddTextEntry("polcarar", "Vapid Caracara BCOS")
AddTextEntry("poldmtr", "Vapid Dominator ASP BCOS")
AddTextEntry("domgt", "Vapid Dominator GT Nightmare")
AddTextEntry("poldmtr2", "Vapid Dominator GTX BCOS")
AddTextEntry("caracaran", "Vapid New Caracara 2020")
AddTextEntry("poltorencer", "Vapid Police Cruiser BCOS")
AddTextEntry("razor", "Vapid Razor")
AddTextEntry("gstriata1", "Vapid Riata CTX")
AddTextEntry("sabot", "Vapid Sabot Concept")
AddTextEntry("polscoutr", "Vapid Scout BCOS")
AddTextEntry("polspeedor", "Vapid Speedo Van BCOS")
AddTextEntry("polstanierr", "Vapid Stanier BCOS")
AddTextEntry("stanier2", "Vapid Stanier Second Generation")
AddTextEntry("fagaloac", "Vulcar Fagaloa Coupe")
AddTextEntry("hotringf", "Willard Hotring Faction")

-- January 2024 Update 2

AddTextEntry("hrgt6r", "HR GT6R")
AddTextEntry("hrwb15", "HR S18 Silhouette")
AddTextEntry("r88", "HR R88")

-- January 2024 Update 3

AddTextEntry("hizoku", "Hizoku")
AddTextEntry("hizokuc", "Hizoku Custom")
AddTextEntry("indiana", "Indiana")
AddTextEntry("indianaxl", "Indiana XL")
AddTextEntry("futelegy", "FutElegy")
AddTextEntry("futol", "FutoL")
AddTextEntry("lemoncom", "LemonComet")
AddTextEntry("lemoneuro", "LemonEuros")
AddTextEntry("lemonpan", "LemonPanorama")
AddTextEntry("lemonrha", "LemonRhapsody")
AddTextEntry("lemonsab", "LemonSabre")
AddTextEntry("lemonvig", "LemonVigero")
AddTextEntry("ratvil", "RATvil")
AddTextEntry("rustpollo", "Rustpollo")
AddTextEntry("seminolel", "SeminoLOL")
AddTextEntry("zion3lem", "Zionlet")
AddTextEntry("patriots", "Patriot S")
AddTextEntry("patriots2", "Patriot S Milspec")
AddTextEntry("gauntlet6str", "Gauntlet 6STR Edition")
AddTextEntry("crowdrunner", "Dominator Crowdrunner")
AddTextEntry("schwarzer6str", "Schwarzer Aggressor 6STR Edition")
AddTextEntry("tmprem", "Premier 200 SS")
AddTextEntry("peanut", "Peanut")
AddTextEntry("cometmw", "Comet Escapist Edition")
AddTextEntry("t20gtr", "T20 GTR")
AddTextEntry("gauntletctx", "Gauntlet Hellfire CTX")
AddTextEntry("ruinervice", "Ruiner Rumbler Vice")
AddTextEntry("velox", "Velox")
AddTextEntry("velox2", "Velox Outlaw")
AddTextEntry("ruiner6str", "Ruiner 450 6STR Custom")
AddTextEntry("reagpr", "Reaper ReMaul Widebody Custom")
AddTextEntry("jd_oraclev12", "Oracle V12")
AddTextEntry("jd_oraclev12a", "Oracle V12 Secret Agent Issue")
AddTextEntry("jd_oraclev12w", "Oracle V12 Touring")
AddTextEntry("jd_oraclexsv12", "Oracle XS V12")
AddTextEntry("jd_oraclexsv12w", "Oracle XS V12 Touring")
AddTextEntry("jesterx", "Jester X-Flow Custom")
AddTextEntry("mesa4x4", "Mesa 4x4 Facelift")
AddTextEntry("contenderc", "Contender Custom")
AddTextEntry("adders", "Adder S")
AddTextEntry("torrence", "Torrence SSO")
AddTextEntry("gresleyh", "Gresley Hellhound")
AddTextEntry("emerusgtr", "Emerus GTR")
AddTextEntry("ellie6str", "Drift Ellie 6STR")
AddTextEntry("stardust", "Stardust")
AddTextEntry("scharmann", "Scharmann")
AddTextEntry("buffaloh", "Buffalo S Hellhound")
AddTextEntry("restovig", "Vigero Restomod 2.0")
AddTextEntry("prally", "Penumbra Cross")
AddTextEntry("mirage", "SP3 Mirage LMP")
AddTextEntry("jestgpr", "Jester ReMaul Widebody Custom")
AddTextEntry("blade3", "Blade Factory Stock")
AddTextEntry("bansheehsw", "Banshee HSW Edition")
AddTextEntry("bandit", "Bandito Buggy")
AddTextEntry("ninef3", "NineF StreetRunner Widebody Custom")
AddTextEntry("gstyosemite1", "Yosemite Trophy Truck")
AddTextEntry("forklift2", "Forklift 2.0")
AddTextEntry("draftgpr", "8F Drafter ReMaul Widebody Custom")
AddTextEntry("cyphart", "Cyphart")
AddTextEntry("tt750", "TT750")
AddTextEntry("mf1", "MF1 Spyder")
AddTextEntry("mf1c", "MF1 Spyder Custom")
AddTextEntry("lynxgpr", "Lynx ReMaul Widebody Custom")
AddTextEntry("ladybird6str", "Ladybird")
AddTextEntry("jesterv12", "Jester V12 Super Secret")
AddTextEntry("hellfirelastcall", "Gauntlet Hellfire LastCall")
AddTextEntry("flivver", "Flivver")
AddTextEntry("expression", "Expression")
AddTextEntry("stingersc", "Stinger SC")
AddTextEntry("stallion4", "Stallion Remastered")
AddTextEntry("celeste", "Celeste")
AddTextEntry("rrhustler", "Hustler Roadster")
AddTextEntry("remusp", "Annis Remus UTE")
AddTextEntry("rebelutility", "Rebel Utility Truck")
AddTextEntry("playboy", "Playboy")
AddTextEntry("pantor", "Racing Panto")
AddTextEntry("elytron", "Elytron Concept")
AddTextEntry("burritor", "Burrito Racing Van")
AddTextEntry("romtuner", "Chariot Romero Hearse Widebody Custom")

-- January 2024 Update 3

AddTextEntry("dubsta22", "2022 Dubsta")
AddTextEntry("oraclestd", "Oracle V12 STD")
AddTextEntry("oracleta", "Oracle V12 STD Time Attack")
AddTextEntry("vaccow", "Pegassi Vacca Rocket Cow")
AddTextEntry("atlas", "Atlas")
AddTextEntry("citi", "Citi")
AddTextEntry("coscarelli", "Coscarelli Hearse")
AddTextEntry("ensenada", "Ensenada Trophy Truck")
AddTextEntry("jackgpr", "Jackal ReMaul Custom")
AddTextEntry("jolly", "Issi Classic Jolly")
AddTextEntry("monroec", "Monroe FR Works Custom")
AddTextEntry("tampar", "Tampa Restomod")
AddTextEntry("cypherwb", "Cypher Widebody Custom")
AddTextEntry("caddyghk", "Caddy Cardboard Racer")
AddTextEntry("dilettanteofrd", "Dilettante Offroader")
AddTextEntry("dochermes", "Doc Hermes")
AddTextEntry("wdump", "Dump Custom")
AddTextEntry("f6200", "F6200")
AddTextEntry("issiv8", "Issi V8 Monster")
AddTextEntry("lbmx", "Super BMX")
AddTextEntry("regina4x4", "Regina 4X4")
AddTextEntry("regina6x6", "Regina 6X6")
AddTextEntry("roundabout", "Roundabout")
AddTextEntry("stance", "Asterope Stance Nation")
AddTextEntry("stanierc", "Drift Stanier")
AddTextEntry("staniert", "Stanier Tow")
AddTextEntry("tacor", "Rocket Taco Truck")
AddTextEntry("tractorcv24", "Tractor Custom V24")
AddTextEntry("sentinelp", "Sentinel Facelift")
AddTextEntry("sentinelp1", "Sentinel Sedan Facelift")
AddTextEntry("ardent3", "Ardent V6 Turbo")
AddTextEntry("sentinelsg4", "Sentinel SG4")
AddTextEntry("seraph3", "Seraph")
AddTextEntry("seraph10", "Seraph XS V10")
AddTextEntry("streiter2", "Streiter Shooting Brake")
AddTextEntry("suranoh", "Surano GT Hardtop")
AddTextEntry("sx6r", "Nagasaki SX6R")
AddTextEntry("sx6r2", "Nagasaki SX6R Stunt Bike")
AddTextEntry("sx6r3", "Nagasaki SX6R Drift Bike")
AddTextEntry("tampad2", "Drift Tampa 6STR Custom")
AddTextEntry("turismocs", "Turismo CS")
AddTextEntry("turismorr", "Turismo R Facelift")
AddTextEntry("ventoso", "Dinka Ventoso Minibike")
AddTextEntry("zionclassic", "Zion Classic Base Model")
AddTextEntry("nebulaw", "Nebula Wagon")
AddTextEntry("nerodrcustom", "Nero Widebody Custom")
AddTextEntry("neross", "Nero Supersport")
AddTextEntry("nerossmk2", "Nero Supersport MkII")
AddTextEntry("phoenixcept", "Interceptor Phoenix")
AddTextEntry("phoenixcept2", "Interceptor Phoenix Clean")
AddTextEntry("phoenixcept3", "Interceptor Phoenix Stealth")
AddTextEntry("sancyb4", "Sancy B4")
AddTextEntry("sandkingxl", "Sandking XL Dually")
AddTextEntry("hellhound", "Gauntlet Hellhound")
AddTextEntry("howitzer", "Howitzer")
AddTextEntry("howitzer2", "Howitzer AC")
AddTextEntry("ingotc", "Ingot VD90R")
AddTextEntry("lentus", "Lentus")
AddTextEntry("majimalm", "Majima LM")
AddTextEntry("driftdominator", "Dominator GTT Kanto Shenanigans")
AddTextEntry("dukesd", "Dukes Hotring Edition")
AddTextEntry("dukedaytona", "Dukes Highway Runner")
AddTextEntry("executioner", "Executioner")
AddTextEntry("feltzer9", "Stirling")
AddTextEntry("gauntletc", "Gauntlet Classic Alt Spec")
AddTextEntry("glendaleks", "Glendale Krieger Special")
AddTextEntry("gruntlet", "BRD Gruntlet 445")
AddTextEntry("bansheepo", "Banshee Phase One")
AddTextEntry("buffaloac", "Buffalo AC Edition")
AddTextEntry("buffalosx", "Buffalo SX Base Model")
AddTextEntry("buffalosxpol", "Buffalo SX Police Cruiser")
AddTextEntry("carbonizzare2", "Carbonizzare Facelift")
AddTextEntry("cheetah8", "Cheetah Facelift")
AddTextEntry("cr727", "CR727 Open Wheeler")
AddTextEntry("sentinelsg3", "Sentinel SG3")
AddTextEntry("sentinelsg3a", "Sentinel SG3 Sedan")
AddTextEntry("sentinelsg3b", "Sentinel SG3 Cabrio")
AddTextEntry("sentinelsg3c", "Sentinel SG3 Touring")
AddTextEntry("sentinelsg3d", "Sentinel SG3 Race Car")
AddTextEntry("eurosold", "Annis Euros Retro")
AddTextEntry("weenyv8", "Issi V8 Custom")
AddTextEntry("urban", "Urban Hot Hatch")
AddTextEntry("thekart", "Drag Kart")
AddTextEntry("gt680", "Quantum GT680")
AddTextEntry("hrsugoip", "Sugoi Pulse")
AddTextEntry("944hr", "P-Turbo R")

-- February 2024 Update 1

AddTextEntry("remustwo", "Remus II")
AddTextEntry("millennial", "Millennial")
AddTextEntry("rapidgte", "Rapid GT GTE")
AddTextEntry("ballerc", "Baller Classic")
AddTextEntry("cascospy", "Casco Spyder")
AddTextEntry("cvalamo", "Alamo 2500LS")
AddTextEntry("dubstaenus", "Enus Dubsta Landaulet")
AddTextEntry("elegyrz", "Elegy RZ Custom")
AddTextEntry("euphoria", "Euphoria")
AddTextEntry("eva", "EVA")
AddTextEntry("fmjgte", "FMJ GTE")
AddTextEntry("h4rxwindsorcus", "Windsor GP Racer")
AddTextEntry("hotwee", "Hotring Weevil")
AddTextEntry("impaler7", "Impaler RT Drag")
AddTextEntry("krust", "Krust")
AddTextEntry("lraft", "The Life Raft")
AddTextEntry("packer3", "Packer Race Truck")
AddTextEntry("pigeon", "Pigeon Police")
AddTextEntry("sbus3", "Derby Bus")
AddTextEntry("scamp", "Scamp")
AddTextEntry("scdtm", "Schwartzer DTM")
AddTextEntry("baikal", "Baikal")
AddTextEntry("tannen", "Tannen")
AddTextEntry("tannen_h", "Tannen Hypermod")
AddTextEntry("towtruck4p", "Tow Truck")
AddTextEntry("vortex2", "Vortex Hovercraft")
AddTextEntry("wastelander2", "Wastelander Restomod")
AddTextEntry("windsor2c", "Windsor Drop 2Door")
AddTextEntry("azatoth", "Azatoth")
AddTextEntry("cheburekr", "Cheburek Rally Spec")
AddTextEntry("chimerac", "Western Chimera Custom")
AddTextEntry("ferocid", "Feroci Custom")
AddTextEntry("mammatus2", "Mammatus Skimmer")
AddTextEntry("molecule", "Molecule")
AddTextEntry("nalamo", "Alamo 2600LS")
AddTextEntry("nebula2", "Nebula Factory Stock")
AddTextEntry("orbita", "orbita")
AddTextEntry("pakunek", "Pakunek")
AddTextEntry("radiantvff", "VFF")
AddTextEntry("corona", "Corona")
AddTextEntry("spirit", "Spirit Chopper")
AddTextEntry("superd3", "Super Diamond S")
AddTextEntry("templar", "Templar")
AddTextEntry("infernus2sepol", "Infernus Classic SE Police Interceptor")
AddTextEntry("argento", "Argento")
AddTextEntry("blistacr", "Blista Cabriolet")
AddTextEntry("boatmobile", "Boatmobile")
AddTextEntry("c3ktem", "3000 Turbo")
AddTextEntry("chopin2", "Chopin Trefl")
AddTextEntry("couchcar", "Couchcar")
AddTextEntry("domellie", "Dominator Ellie")
AddTextEntry("dumps", "RC Toy Dump")
AddTextEntry("fugitivev8", "Fugitive V8 Race Car")
AddTextEntry("hotringfr", "Hotring Fortune")
AddTextEntry("howler", "Howler")
AddTextEntry("landroamer", "Landroamer")
AddTextEntry("leo", "Leo")
AddTextEntry("mark1", "Mark 1")
AddTextEntry("matador", "Matador")
AddTextEntry("maverick2", "Emergency Maverick")
AddTextEntry("newsmav", "Weasel News Maverick")
AddTextEntry("nightblade2", "Nightblade Classic")
AddTextEntry("niner", "Nine R")
AddTextEntry("paradrop", "Paragon Drop")
AddTextEntry("proff", "PR4 Formula Offroad")
AddTextEntry("pthrust", "Thrust LSPD Bike")
AddTextEntry("sabrecab", "Sabre Turbo Cabriolet")
AddTextEntry("saltflat", "Saltflat")
AddTextEntry("shergauntlet", "Sheriff Gauntlet AC")
AddTextEntry("slave", "Slave")
AddTextEntry("supersanchez", "Super Sanchez")
AddTextEntry("vesper", "Vesper")
AddTextEntry("torerojp", "Torero Japanese Police Interceptor")
AddTextEntry("Westward", "Westward")
AddTextEntry("zombiev8", "Zombie V8 Custom")
AddTextEntry("domgtcoupe", "Dominator GT Coupe")
AddTextEntry("sentinelmk4", "Sentinel Mk4")
AddTextEntry("sentinelmk4gtr", "Sentinel Mk4 GTR")

-- March 2024 Update 1

AddTextEntry("barrage", "Barrage Civie")
AddTextEntry("blistawide", "Blista Widebody Custom")
AddTextEntry("ccadeesv", "Cavalcade ESV")
AddTextEntry("ccadefxt", "Cavalcade FXT")
AddTextEntry("com20gpr", "Comet R20")
AddTextEntry("com21gpr", "Comet SR20")
AddTextEntry("cometr", "Comet R")
AddTextEntry("cometretro", "Comet Retro Stock")
AddTextEntry("cometrs", "Comet RS")
AddTextEntry("crazybus", "Crazy Bus")
AddTextEntry("deviant2", "1970 Deviant")
AddTextEntry("elegyr", "Elegy RH5 Rally Car")
AddTextEntry("elegyw", "Elegy RH5 Wagon")
AddTextEntry("futope", "Futo Ydrop Custom")
AddTextEntry("gwoods", "Schyster Greenwood Classic")
AddTextEntry("jb700s", "JB700 S")
AddTextEntry("kartcross", "Kart Cross")
AddTextEntry("kriegerc", "Krieger BPX 32B")
AddTextEntry("kurumac", "Kuruma Custom")
AddTextEntry("kurumata", "Kuruma Time Attack")
AddTextEntry("kurumata2", "Kuruma Time Attack MkII")
AddTextEntry("mesaxl", "Mesa XL Gator")
AddTextEntry("nsandstorm", "Sandstorm")
AddTextEntry("nsandstorm2", "Sandstorm Dually")
AddTextEntry("hellenstorm", "Sandstorm Hellenbach")
AddTextEntry("nwkuruma", "Kuruma Northwind Spec")
AddTextEntry("policebm", "Stanier Burnout Machine")
AddTextEntry("polimpaler", "Impaler SZ Police Cruiser")
AddTextEntry("r255", "Ingot R255")
AddTextEntry("raidenz", "Raiden Z")
AddTextEntry("ratdemon", "Bobcat RatDemon")
AddTextEntry("savestrare", "Savestra RE")
AddTextEntry("schafter3rs", "Schafter RS")
AddTextEntry("sentineldm", "Sentinel SG3 Drift Missile")
AddTextEntry("spmp", "Schyster PMP 600")
AddTextEntry("stratumc", "Stratum Custom")
AddTextEntry("streetwalk", "Turismo Classic Streetwalk Edition")
AddTextEntry("sultanrsv8", "Sultan RS V8 MkII")
AddTextEntry("tachyon", "Tachyon")
AddTextEntry("tartaro", "Tartaro")
AddTextEntry("turismo2lm", "Turismo Classic Le Mans")
AddTextEntry("gbbisonhf", "Bison HF")
AddTextEntry("gbclubxr", "Club XR")
AddTextEntry("gbdominatorgsx", "Dominator GSX")
AddTextEntry("gbeon", "Eon")
AddTextEntry("gbmogulrs", "Mogul RS")
AddTextEntry("gbneonct", "Neon CT")
AddTextEntry("gbschlagenr", "Schlagen Roadster")
AddTextEntry("gbschlagensp", "Sclagen SP")
AddTextEntry("gbschwartzers", "Schwartzer S")
AddTextEntry("gbstarlight", "Starlight")
AddTextEntry("gbsultanrsx", "Sultan RSX")
AddTextEntry("gbtahomagt", "Tahoma GT")

-- March 2024 Update 2

AddTextEntry("aerocab", "Aerocab")
AddTextEntry("aleutianxl", "Aleutian XL")
AddTextEntry("boorbc", "Boor Custom 4 Seater")
AddTextEntry("burritopw", "Burrito Power Wheels")
AddTextEntry("caracara6x6", "Civilian Caracara 6x6")
AddTextEntry("cheetahrod", "Cheetah Classic Roadster")
AddTextEntry("cheetahrod2", "Cheetah Classic Cabriolet")
AddTextEntry("comet6scw", "Comet S2 Widebody Custom")
AddTextEntry("cometrr", "Comet RR Custom")
AddTextEntry("contenderbaja", "Contender Baja Spec")
AddTextEntry("coqgte", "Coquette GTE")
AddTextEntry("coquetteds", "Coquette Drift Spec")
AddTextEntry("coqvr", "Coquette VR1")
AddTextEntry("dom645", "Dominator 645")
AddTextEntry("dom645t", "Dominator 645 Fastback")
AddTextEntry("dukes4", "Dukes Cobra")
AddTextEntry("dyosemite", "2000 Yosemite")
AddTextEntry("espexecutive", "Esperanto Executive")
AddTextEntry("eudorac", "Eudora Convertible")
AddTextEntry("glenzoku", "Zokusha Glendale")
AddTextEntry("italirsxrod", "Itali RSX Roadster")
AddTextEntry("linerunner", "Linerunner")
AddTextEntry("ncavalcade", "Cavalcade III")
AddTextEntry("oceanic", "Oceanic")
AddTextEntry("panorama", "Panorama")
AddTextEntry("panoramab", "Trailer Trash Panorama")
AddTextEntry("panoramas", "Panoramas")
AddTextEntry("paragonxr", "Paragon XR FR Works")
AddTextEntry("penman", "Penman")
AddTextEntry("primolx", "Primo LX")
AddTextEntry("r300w", "300R Widebody Custom")
AddTextEntry("sabre", "Sabre")
AddTextEntry("snbladec", "Nightblade Custom Ape Hanger")
AddTextEntry("thraxs", "Thrax S")
AddTextEntry("tyrus2", "Tyrus S")
AddTextEntry("tyrusgtr", "Tyrus GTR")
AddTextEntry("vigerozxwb", "Vigero ZX Widebody Custom")
AddTextEntry("vtvicechee", "Unmarked Cheetah Classic Vice PD")
AddTextEntry("warrener3", "Warrener Custom")

-- March 2024 Update 3

AddTextEntry("bsariant", "Ariant BayShore Spec")
AddTextEntry("bscomet", "Comet S2 BayShore Spec")
AddTextEntry("bselegy", "Elegy RH5 BayShore Spec")
AddTextEntry("bselegy2", "Elegy RH5 BayShore Spec MkII")
AddTextEntry("bstorero", "Torero Classic BayShore Spec")
AddTextEntry("bstorero2", "Torero Classic BayShore Spec MkII")
AddTextEntry("bsviseris", "Viseris BayShore Spec")
AddTextEntry("trubuffalo", "Buffalo SX Police Cruiser")
AddTextEntry("trubuffalo2", "Buffalo SX Police Cruiser II")
AddTextEntry("umkbuffalo", "Buffalo SX Unmarked Cruiser")
AddTextEntry("weevilf6", "Ruff Weld Weevil Custom")
AddTextEntry("bloke", "Bloke the Fella")
AddTextEntry("sulboost", "Sultan Backyard Boost")
AddTextEntry("kriegerty2", "Krieger Type II")
AddTextEntry("blistata", "Blista Time Attack Spec")
AddTextEntry("zr350ta", "ZR350 Time Attack Spec")
AddTextEntry("pantoes", "Panto Engine Swapped Abomination")
AddTextEntry("type1", "Type I")
AddTextEntry("dproto", "Deluxo Prototype")
AddTextEntry("entity11", "Entity XXR-11")
AddTextEntry("furiawb", "Furia Widebody Custom")
AddTextEntry("hurricane", "Hurricane")
AddTextEntry("lpbagger", "Marabunta")
AddTextEntry("lpchopper", "Blackwater")
AddTextEntry("peacemaker", "Peacemaker 2-Door")
AddTextEntry("peacemaker2", "Peacemaker 4-Door")
AddTextEntry("peacemaker3", "Peacemaker Six Wheeler")
AddTextEntry("r70k", "R70K")
AddTextEntry("s98", "S98")
AddTextEntry("sg1150", "SG1150")
AddTextEntry("sombrero", "Sombrero")
AddTextEntry("toros2", "Toros Remastered Edition")
AddTextEntry("weevilo", "Weevil Outlaw")
AddTextEntry("zorya01", "Zorya")
AddTextEntry("apocalyptic", "Apocalyptic Runner")
AddTextEntry("audace", "Audace")
AddTextEntry("bf900", "BF900")
AddTextEntry("bfbenito", "Benito")
AddTextEntry("burgerw", "Bleeder Burger Wagon")
AddTextEntry("clkscc", "A50 VTOL Warmonger")
AddTextEntry("polalamog", "Alamo Police Wagon Ghost")
AddTextEntry("polalamog2", "Alamo 2600LS Police Wagon Ghost")
AddTextEntry("polbisong", "Bison Police Pickup Ghost")
AddTextEntry("polbuffalog", "Buffalo SX Ghost Interceptor")
AddTextEntry("polbuffalog2", "Buffalo S Ghost Interceptor")
AddTextEntry("polcarag", "Caracara Police Pickup Ghost")
AddTextEntry("polcoquetteg", "Coquette Ghost Interceptor")
AddTextEntry("poldmntg", "Dominator GTX Ghost Interceptor")
AddTextEntry("polfugitiveg", "Fugitive Ghost Cruiser")
AddTextEntry("polgauntletg", "Gauntlet Hellfire Ghost Interceptor")
AddTextEntry("polgresleyg", "Gresley Police Wagon Ghost")
AddTextEntry("polroamerg", "Landroamer Police Wagon Ghost")
AddTextEntry("polscoutg", "Scout Police Wagon Ghost")
AddTextEntry("polstalkerg", "Landstalker Police Wagon Ghost")
AddTextEntry("polstanierg", "Stanier Ghost Cruiser")
AddTextEntry("poltorenceg", "Torrence Ghost Cruiser")
AddTextEntry("polvigerog", "Vigero ZX Ghost Interceptor")

-- April 2024 Update 1

AddTextEntry("bheist", "Buffalo Heist")
AddTextEntry("cheetahfel", "Cheetah Classic Feline")
AddTextEntry("coquettewb", "Coquette SilentM Custom Widebody")
AddTextEntry("deluxowb", "CyberDeluxo")
AddTextEntry("dingo", "Dingo")
AddTextEntry("dingo2", "Dingo SS")
AddTextEntry("domc", "Dominator Classic")
AddTextEntry("dominatorc2", "Hellenbach 428 SSC")
AddTextEntry("dominatorgtc", "Dominator Classic GTC")
AddTextEntry("etimesoy", "Etimesoy")
AddTextEntry("f620d", "F620 Drop")
AddTextEntry("freeway", "Freeway")
AddTextEntry("minivan3a", "Minivan Remastered")
AddTextEntry("minivan3b", "Minivan Bagged")
AddTextEntry("gstap1", "Parathugagon")
AddTextEntry("gstghell1", "Gauntlet Hellfire CTX Version II")
AddTextEntry("hgasser", "Hustler Gasser")
AddTextEntry("kamswb", "Kamacho SWB")
AddTextEntry("m420", "Monroe S.O.T.W")
AddTextEntry("maverickiv", "Maverick IV")
AddTextEntry("maverickiv2", "Maverick IV 2.0")
AddTextEntry("maverickv", "Maverick V")
AddTextEntry("maverickv2", "Maverick V 2.0")
AddTextEntry("nspeedo", "Speedo Transporter")
AddTextEntry("policejpheli", "TMPD SuperVolito")
AddTextEntry("potty", "Potty")
AddTextEntry("raidengrb", "Raiden GRB")
AddTextEntry("rocketfire", "RocketFire")
AddTextEntry("ruinerafd", "Ruiner UTE")
AddTextEntry("sandkingd", "Sandking Custom Diesel Dually")
AddTextEntry("sc_dominatorwb", "Dominator SC Widebody Custom")
AddTextEntry("sentinel_rts", "Sentinel RTS")
AddTextEntry("stanierdrift", "Stanier Drift Custom")
AddTextEntry("tampag", "Tampa Gasser")
AddTextEntry("terl300", "L300")
AddTextEntry("timekeeper", "Gauntlet Classic Timekeeper")
AddTextEntry("torrumk", "Torrence Unmarked Interceptor")
AddTextEntry("tractorsmall", "Agroboy")
AddTextEntry("tunak", "Tunak")
AddTextEntry("valkyrieg1", "Valkyrie Gunship US Army")
AddTextEntry("valkyrieg2", "Valkyrie Gunship USAF")
AddTextEntry("valkyrieg3", "Valkyrie Gunship US Marines")
AddTextEntry("fibvalk", "Valkyrie FIB")
AddTextEntry("noosevalk", "Valkyrie NOOSE")
AddTextEntry("usafvalk", "Valkyrie USAF")
AddTextEntry("usarmyvalk", "Valkyrie US Army")
AddTextEntry("usmvalk", "Valkyrie US Marines")
AddTextEntry("verin", "Verin")
AddTextEntry("warrenerc", "Warrener Coupe")
AddTextEntry("yds", "Yosemite Drag Spec")
AddTextEntry("ysf", "Yosemite Factory Stock")

-- June 2024 Update 1

AddTextEntry("ardentc", "Ardent Classic")
AddTextEntry("astronc", "Astron Widebody Custom")
AddTextEntry("banana", "Le Banana Kar")
AddTextEntry("brisket", "Brisket")
AddTextEntry("brisket2", "Brisket Rally Spec")
AddTextEntry("brisket3", "Brisket Gasser")
AddTextEntry("buffalowb", "Buffalo STX Widebody Custom")
AddTextEntry("coquette8", "Coquette Phobos")
AddTextEntry("dom204", "Dominator 204")
AddTextEntry("dragqueen", "Drag Queen")
AddTextEntry("duness", "DuneSS")
AddTextEntry("elegyrh6", "Elegy RH6")
AddTextEntry("emerusfl", "Emerus Facelift")
AddTextEntry("fdl300", "L300 Emergency")
AddTextEntry("gp1i", "GP1 Improved")
AddTextEntry("gspeedster", "Speedster")
AddTextEntry("hr530", "530R")
AddTextEntry("hrf38s", "Furor 38 Sedan")
AddTextEntry("hrsolas", "Solasta X")
AddTextEntry("imperial", "Imperial Minivan")
AddTextEntry("jubilee8", "Jubilee Facelift")
AddTextEntry("kurumahr", "Karin Kuruma HR Edition")
AddTextEntry("nriata", "Riata TX")
AddTextEntry("odyssey", "Odyssey")
AddTextEntry("pedalbeer", "Beer Pedal Bus")
AddTextEntry("raiden2", "Raiden Base Model")
AddTextEntry("ratloaderc", "Ratloader Custom")
AddTextEntry("rcbandito2", "RC Bandito Buggy")
AddTextEntry("sm-sanctus", "Lighting Sanctus")
AddTextEntry("ssg_ballerstd", "Baller STD Platinum Edition")
AddTextEntry("suranoe", "Surano Electric Motion")
AddTextEntry("s18h", "S18 Silhouette V2.0")
AddTextEntry("fr36c", "FR36")

end)
