CLOTHES = {
	['red'] = {
		['assault'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 115,texture = 16},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 58,texture = 0},{component_id = 4,drawable = 62,texture = 0},{component_id = 5,drawable = 0,texture = 0},{component_id = 6,drawable = 27,texture = 0},{component_id = 7,drawable = 118,texture = 0},{component_id = 8,drawable = 143,texture = 0},{component_id = 9,drawable = 19,texture = 0},{component_id = 10,drawable = 77,texture = 0},{component_id = 11,drawable = 213,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = -1,drawable = -1,prop_id = 0},{texture = 0,drawable = 10,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 0,drawable = 8,prop_id = 6},{texture = 0,drawable = 5,prop_id = 7}}},
		['medic'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 12,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 92,texture = 0},{component_id = 4,drawable = 143,texture = 0},{component_id = 5,drawable = 0,texture = 0},{component_id = 6,drawable = 27,texture = 0},{component_id = 7,drawable = 5,texture = 0},{component_id = 8,drawable = 102,texture = 0},{component_id = 9,drawable = 17,texture = 0},{component_id = 10,drawable = 45,texture = 0},{component_id = 11,drawable = 337,texture = 3}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 4,drawable = 6,prop_id = 0},{texture = 0,drawable = 8,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 0,drawable = 8,prop_id = 6},{texture = 0,drawable = 5,prop_id = 7}}},
		['engineer'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 161,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 164,texture = 1},{component_id = 4,drawable = 91,texture = 0},{component_id = 5,drawable = 57,texture = 0},{component_id = 6,drawable = 92,texture = 0},{component_id = 7,drawable = 53,texture = 0},{component_id = 8,drawable = 95,texture = 0},{component_id = 9,drawable = 4,texture = 0},{component_id = 10,drawable = 66,texture = 0},{component_id = 11,drawable = 325,texture = 1}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = -1,drawable = -1,prop_id = 0},{texture = 0,drawable = 21,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 0,drawable = 8,prop_id = 6},{texture = 0,drawable = 5,prop_id = 7}}},
		['heavy'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 104,texture = 25},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 110,texture = 3},{component_id = 4,drawable = 143,texture = 0},{component_id = 5,drawable = 22,texture = 0},{component_id = 6,drawable = 27,texture = 0},{component_id = 7,drawable = 147,texture = 0},{component_id = 8,drawable = 60,texture = 0},{component_id = 9,drawable = 6,texture = 0},{component_id = 10,drawable = 0,texture = 0},{component_id = 11,drawable = 50,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 127,prop_id = 0},{texture = 3,drawable = 24,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}},
		['scout'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 52,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 164,texture = 1},{component_id = 4,drawable = 119,texture = 0},{component_id = 5,drawable = 61,texture = 0},{component_id = 6,drawable = 26,texture = 1},{component_id = 7,drawable = 12,texture = 1},{component_id = 8,drawable = 120,texture = 0},{component_id = 9,drawable = 7,texture = 0},{component_id = 10,drawable = 44,texture = 0},{component_id = 11,drawable = 325,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 45,prop_id = 0},{texture = 0,drawable = 11,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 0,drawable = 46,prop_id = 6},{texture = 0,drawable = 5,prop_id = 7}}}
	},
	['blue'] = {
		['assault'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 159,texture = 1},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 164,texture = 2},{component_id = 4,drawable = 85,texture = 0},{component_id = 5,drawable = 60,texture = 0},{component_id = 6,drawable = 63,texture = 2},{component_id = 7,drawable = 149,texture = 4},{component_id = 8,drawable = 64,texture = 1},{component_id = 9,drawable = 3,texture = 0},{component_id = 10,drawable = 70,texture = 1},{component_id = 11,drawable = 257,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 1,drawable = 117,prop_id = 0},{texture = 1,drawable = 11,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 1,drawable = 31,prop_id = 6},{texture = 0,drawable = 1,prop_id = 7}}},
		['medic'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 50,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 91,texture = 0},{component_id = 4,drawable = 114,texture = 1},{component_id = 5,drawable = 39,texture = 0},{component_id = 6,drawable = 62,texture = 4},{component_id = 7,drawable = 1,texture = 1},{component_id = 8,drawable = 98,texture = 1},{component_id = 9,drawable = 2,texture = 0},{component_id = 10,drawable = 8,texture = 0},{component_id = 11,drawable = 310,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 45,prop_id = 0},{texture = 1,drawable = 11,prop_id = 1},{texture = 1,drawable = 3,prop_id = 2},{texture = 0,drawable = 1,prop_id = 6},{texture = 0,drawable = 1,prop_id = 7}}},
		['engineer'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 104,texture = 25},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 109,texture = 0},{component_id = 4,drawable = 108,texture = 1},{component_id = 5,drawable = 65,texture = 0},{component_id = 6,drawable = 63,texture = 2},{component_id = 7,drawable = 112,texture = 2},{component_id = 8,drawable = 63,texture = 1},{component_id = 9,drawable = 27,texture = 0},{component_id = 10,drawable = 8,texture = 0},{component_id = 11,drawable = 144,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 147,prop_id = 0},{texture = 0,drawable = 15,prop_id = 1},{texture = 0,drawable = 37,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}},
		['heavy'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 158,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 110,texture = 3},{component_id = 4,drawable = 114,texture = 1},{component_id = 5,drawable = 33,texture = 2},{component_id = 6,drawable = 62,texture = 4},{component_id = 7,drawable = 139,texture = 0},{component_id = 8,drawable = 99,texture = 1},{component_id = 9,drawable = 8,texture = 0},{component_id = 10,drawable = 2,texture = 0},{component_id = 11,drawable = 139,texture = 3}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 92,prop_id = 0},{texture = 1,drawable = 2,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}},
		['scout'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 169,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 109,texture = 0},{component_id = 4,drawable = 110,texture = 0},{component_id = 5,drawable = 80,texture = 0},{component_id = 6,drawable = 63,texture = 4},{component_id = 7,drawable = 53,texture = 1},{component_id = 8,drawable = 120,texture = 2},{component_id = 9,drawable = 23,texture = 0},{component_id = 10,drawable = 44,texture = 1},{component_id = 11,drawable = 149,texture = 1}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 45,prop_id = 0},{texture = 1,drawable = 11,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}}
	},
	['green'] = {
		['assault'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 159,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 165,texture = 0},{component_id = 4,drawable = 108,texture = 0},{component_id = 5,drawable = 58,texture = 0},{component_id = 6,drawable = 63,texture = 0},{component_id = 7,drawable = 1,texture = 0},{component_id = 8,drawable = 118,texture = 0},{component_id = 9,drawable = 24,texture = 0},{component_id = 10,drawable = 0,texture = 0},{component_id = 11,drawable = 7,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 117,prop_id = 0},{texture = 2,drawable = 11,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = 0,drawable = 1,prop_id = 6},{texture = 0,drawable = 1,prop_id = 7}}},
		['medic'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 50,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 85,texture = 0},{component_id = 4,drawable = 106,texture = 0},{component_id = 5,drawable = 38,texture = 0},{component_id = 6,drawable = 63,texture = 0},{component_id = 7,drawable = 126,texture = 0},{component_id = 8,drawable = 63,texture = 0},{component_id = 9,drawable = 22,texture = 0},{component_id = 10,drawable = 63,texture = 0},{component_id = 11,drawable = 114,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 118,prop_id = 0},{texture = 0,drawable = 11,prop_id = 1},{texture = 0,drawable = 4,prop_id = 2},{texture = 0,drawable = 32,prop_id = 6},{texture = 0,drawable = 1,prop_id = 7}}},
		['engineer'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 159,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 16,texture = 0},{component_id = 4,drawable = 108,texture = 0},{component_id = 5,drawable = 34,texture = 0},{component_id = 6,drawable = 63,texture = 0},{component_id = 7,drawable = 112,texture = 0},{component_id = 8,drawable = 119,texture = 0},{component_id = 9,drawable = 26,texture = 0},{component_id = 10,drawable = 0,texture = 0},{component_id = 11,drawable = 149,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 78,prop_id = 0},{texture = 3,drawable = 11,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}},
		['heavy'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 158,texture = 1},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 110,texture = 3},{component_id = 4,drawable = 114,texture = 0},{component_id = 5,drawable = 33,texture = 0},{component_id = 6,drawable = 63,texture = 0},{component_id = 7,drawable = 0,texture = 0},{component_id = 8,drawable = 99,texture = 0},{component_id = 9,drawable = 25,texture = 0},{component_id = 10,drawable = 2,texture = 0},{component_id = 11,drawable = 8,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = 255,highlight = 255},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 94,prop_id = 0},{texture = 0,drawable = 2,prop_id = 1},{texture = -1,drawable = -1,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}},
		['scout'] = {components = {{component_id = 0,drawable = 0,texture = 0},{component_id = 1,drawable = 204,texture = 0},{component_id = 2,drawable = 0,texture = 0},{component_id = 3,drawable = 154,texture = 14},{component_id = 4,drawable = 114,texture = 0},{component_id = 5,drawable = 59,texture = 0},{component_id = 6,drawable = 62,texture = 0},{component_id = 7,drawable = 53,texture = 0},{component_id = 8,drawable = 120,texture = 1},{component_id = 9,drawable = 1,texture = 0},{component_id = 10,drawable = 11,texture = 0},{component_id = 11,drawable = 149,texture = 0}},headOverlays = {beard = {opacity = 0,style = 0,color = 0},blemishes = {opacity = 0,style = 0,color = 0},moleAndFreckles = {opacity = 0,style = 0,color = 0},chestHair = {opacity = 0,style = 0,color = 0},makeUp = {opacity = 0,style = 0,color = 0},bodyBlemishes = {opacity = 0,style = 0,color = 0},ageing = {opacity = 0,style = 0,color = 0},eyebrows = {opacity = 0,style = 0,color = 0},sunDamage = {opacity = 0,style = 0,color = 0},lipstick = {opacity = 0,style = 0,color = 0},complexion = {opacity = 0,style = 0,color = 0},blush = {opacity = 0,style = 0,color = 0}},eyeColor = -1,headBlend = {shapeSecond = 0,skinFirst = 0,shapeMix = 0,skinMix = 0,shapeFirst = 0,skinSecond = 0},hair = {style = 0,color = -1,highlight = -1},model = mp_m_freemode_01,faceFeatures = {nosePeakSize = 0,eyeBrownHigh = 0,chinBoneLenght = 0,eyesOpening = 0,neckThickness = 0,chinBoneSize = 0,chinBoneLowering = 0,noseWidth = 0,cheeksWidth = 0,cheeksBoneHigh = 0,nosePeakHigh = 0,noseBoneHigh = 0,eyeBrownForward = 0,nosePeakLowering = 0,cheeksBoneWidth = 0,chinHole = 0,jawBoneBackSize = 0,jawBoneWidth = 0,lipsThickness = 0,noseBoneTwist = 0},tattoos = {},props = {{texture = 0,drawable = 118,prop_id = 0},{texture = 0,drawable = 11,prop_id = 1},{texture = 0,drawable = 38,prop_id = 2},{texture = -1,drawable = -1,prop_id = 6},{texture = -1,drawable = -1,prop_id = 7}}}
	},
	['staff'] = {
		{components = {{drawable = 0,texture = 0,component_id = 0},{drawable = 18,texture = 0,component_id = 2},{drawable = 0,texture = 0,component_id = 5},{drawable = 0,texture = 0,component_id = 7},{drawable = 0,texture = 0,component_id = 9},{drawable = 0,texture = 0,component_id = 10},{drawable = 15,texture = 0,component_id = 8},{drawable = 285,texture = 0,component_id = 11},{drawable = 147,texture = 0,component_id = 1},{drawable = 24,texture = 0,component_id = 6},{drawable = 112,texture = 0,component_id = 4},{drawable = 213,texture = 0,component_id = 3}},tattoos = {},eyeColor = 0,model = mp_m_freemode_01,hair = {color = 14,style = 18,highlight = 14},props = {{prop_id = 0,drawable = -1,texture = -1},{prop_id = 1,drawable = -1,texture = -1},{prop_id = 2,drawable = -1,texture = -1},{prop_id = 6,drawable = -1,texture = -1},{prop_id = 7,drawable = -1,texture = -1}},faceFeatures = {lipsThickness = 0,chinHole = 0,jawBoneBackSize = 0,nosePeakHigh = 0,noseBoneTwist = 0,eyesOpening = 0,jawBoneWidth = 0,noseBoneHigh = 0,eyeBrownForward = 0,cheeksWidth = 0,neckThickness = 0,eyeBrownHigh = 0,chinBoneLenght = 0,cheeksBoneWidth = 0,cheeksBoneHigh = 0,nosePeakSize = 0,noseWidth = 0,chinBoneLowering = 0,nosePeakLowering = 0,chinBoneSize = 0},headOverlays = {moleAndFreckles = {color = 0,style = 0,opacity = 0},chestHair = {color = 0,style = 0,opacity = 0},complexion = {color = 0,style = 0,opacity = 0},blush = {color = 0,style = 0,opacity = 0},ageing = {color = 0,style = 0,opacity = 0},beard = {color = 0,style = 0,opacity = 0.5},sunDamage = {color = 0,style = 0,opacity = 0},eyebrows = {color = 0,style = 0,opacity = 0},makeUp = {color = 0,style = 0,opacity = 0},lipstick = {color = 0,style = 0,opacity = 0},blemishes = {color = 0,style = 0,opacity = 0.2},bodyBlemishes = {color = 0,style = 0,opacity = 0}},headBlend = {shapeMix = 0,shapeFirst = 0,skinFirst = 0,shapeSecond = 0,skinSecond = 0,skinMix = 0}}
		-- CHRISTMAS: {components={{texture=0,drawable=0,component_id=0},{texture=0,drawable=200,component_id=1},{texture=0,drawable=257,component_id=2},{texture=0,drawable=217,component_id=3},{texture=0,drawable=241,component_id=4},{texture=0,drawable=0,component_id=5},{texture=0,drawable=223,component_id=6},{texture=0,drawable=0,component_id=7},{texture=4,drawable=220,component_id=8},{texture=0,drawable=0,component_id=9},{texture=0,drawable=0,component_id=10},{texture=0,drawable=300,component_id=11}},headBlend={shapeFirst=0,shapeSecond=0,skinSecond=0,skinFirst=0,skinMix=0,shapeMix=0},hair={style=0,highlight=2,color=5},props={{drawable=-1,prop_id=0,texture=-1},{drawable=-1,prop_id=1,texture=-1},{drawable=-1,prop_id=2,texture=-1},{drawable=-1,prop_id=6,texture=-1},{drawable=-1,prop_id=7,texture=-1}},faceFeatures={eyeBrownHigh=0,noseBoneTwist=0,cheeksBoneWidth=0,noseBoneHigh=0,chinBoneLowering=0,cheeksBoneHigh=0,neckThickness=0,cheeksWidth=0,chinBoneLenght=0,jawBoneBackSize=0,nosePeakSize=0,eyesOpening=0,lipsThickness=0,noseWidth=0,eyeBrownForward=0,jawBoneWidth=0,chinBoneSize=0,nosePeakLowering=0,chinHole=0,nosePeakHigh=0},headOverlays={sunDamage={color=0,style=0,opacity=0},blush={color=0,style=0,opacity=0},bodyBlemishes={color=0,style=0,opacity=0},eyebrows={color=0,style=0,opacity=0},beard={color=0,style=0,opacity=0},chestHair={color=0,style=0,opacity=0},lipstick={color=0,style=0,opacity=0},makeUp={color=0,style=0,opacity=0},ageing={color=0,style=0,opacity=0},moleAndFreckles={color=0,style=0,opacity=0},blemishes={color=0,style=0,opacity=0},complexion={color=0,style=0,opacity=0}},eyeColor=-1,model=mp_m_freemode_01},
		-- CHRISTMAS: {components={{texture=0,drawable=0,component_id=0},{texture=0,drawable=407,component_id=1},{texture=0,drawable=257,component_id=2},{texture=0,drawable=217,component_id=3},{texture=0,drawable=343,component_id=4},{texture=0,drawable=0,component_id=5},{texture=2,drawable=12,component_id=6},{texture=1,drawable=350,component_id=7},{texture=0,drawable=15,component_id=8},{texture=0,drawable=0,component_id=9},{texture=0,drawable=0,component_id=10},{texture=0,drawable=625,component_id=11}},headBlend={shapeFirst=0,shapeSecond=0,skinSecond=0,skinFirst=0,skinMix=0,shapeMix=0},hair={style=0,highlight=2,color=5},props={{drawable=-1,prop_id=0,texture=-1},{drawable=-1,prop_id=1,texture=-1},{drawable=-1,prop_id=2,texture=-1},{drawable=-1,prop_id=6,texture=-1},{drawable=-1,prop_id=7,texture=-1}},faceFeatures={eyeBrownHigh=0,noseBoneTwist=0,cheeksBoneWidth=0,noseBoneHigh=0,chinBoneLowering=0,cheeksBoneHigh=0,neckThickness=0,cheeksWidth=0,chinBoneLenght=0,jawBoneBackSize=0,nosePeakSize=0,eyesOpening=0,lipsThickness=0,noseWidth=0,eyeBrownForward=0,jawBoneWidth=0,chinBoneSize=0,nosePeakLowering=0,chinHole=0,nosePeakHigh=0},headOverlays={sunDamage={color=0,style=0,opacity=0},blush={color=0,style=0,opacity=0},bodyBlemishes={color=0,style=0,opacity=0},eyebrows={color=0,style=0,opacity=0},beard={color=0,style=0,opacity=0},chestHair={color=0,style=0,opacity=0},lipstick={color=0,style=0,opacity=0},makeUp={color=0,style=0,opacity=0},ageing={color=0,style=0,opacity=0},moleAndFreckles={color=0,style=0,opacity=0},blemishes={color=0,style=0,opacity=0},complexion={color=0,style=0,opacity=0}},eyeColor=-1,model=mp_m_freemode_01},
		-- CHRISTMAS: {components={{texture=0,drawable=0,component_id=0},{texture=0,drawable=406,component_id=1},{texture=0,drawable=257,component_id=2},{texture=0,drawable=217,component_id=3},{texture=0,drawable=342,component_id=4},{texture=0,drawable=0,component_id=5},{texture=0,drawable=302,component_id=6},{texture=0,drawable=350,component_id=7},{texture=0,drawable=15,component_id=8},{texture=0,drawable=0,component_id=9},{texture=0,drawable=0,component_id=10},{texture=0,drawable=622,component_id=11}},headBlend={shapeFirst=0,shapeSecond=0,skinSecond=0,skinFirst=0,skinMix=0,shapeMix=0},hair={style=0,highlight=2,color=5},props={{drawable=-1,prop_id=0,texture=-1},{drawable=-1,prop_id=1,texture=-1},{drawable=-1,prop_id=2,texture=-1},{drawable=-1,prop_id=6,texture=-1},{drawable=-1,prop_id=7,texture=-1}},faceFeatures={eyeBrownHigh=0,noseBoneTwist=0,cheeksBoneWidth=0,noseBoneHigh=0,chinBoneLowering=0,cheeksBoneHigh=0,neckThickness=0,cheeksWidth=0,chinBoneLenght=0,jawBoneBackSize=0,nosePeakSize=0,eyesOpening=0,lipsThickness=0,noseWidth=0,eyeBrownForward=0,jawBoneWidth=0,chinBoneSize=0,nosePeakLowering=0,chinHole=0,nosePeakHigh=0},headOverlays={sunDamage={color=0,style=0,opacity=0},blush={color=0,style=0,opacity=0},bodyBlemishes={color=0,style=0,opacity=0},eyebrows={color=0,style=0,opacity=0},beard={color=0,style=0,opacity=0},chestHair={color=0,style=0,opacity=0},lipstick={color=0,style=0,opacity=0},makeUp={color=0,style=0,opacity=0},ageing={color=0,style=0,opacity=0},moleAndFreckles={color=0,style=0,opacity=0},blemishes={color=0,style=0,opacity=0},complexion={color=0,style=0,opacity=0}},eyeColor=-1,model=mp_m_freemode_01},
		-- CHRISTMAS: {components={{texture=0,drawable=0,component_id=0},{texture=0,drawable=402,component_id=1},{texture=0,drawable=257,component_id=2},{texture=0,drawable=217,component_id=3},{texture=0,drawable=341,component_id=4},{texture=0,drawable=0,component_id=5},{texture=0,drawable=301,component_id=6},{texture=0,drawable=0,component_id=7},{texture=0,drawable=15,component_id=8},{texture=0,drawable=0,component_id=9},{texture=0,drawable=0,component_id=10},{texture=0,drawable=621,component_id=11}},headBlend={shapeFirst=0,shapeSecond=0,skinSecond=0,skinFirst=0,skinMix=0,shapeMix=0},hair={style=0,highlight=2,color=5},props={{drawable=-1,prop_id=0,texture=-1},{drawable=-1,prop_id=1,texture=-1},{drawable=-1,prop_id=2,texture=-1},{drawable=-1,prop_id=6,texture=-1},{drawable=-1,prop_id=7,texture=-1}},faceFeatures={eyeBrownHigh=0,noseBoneTwist=0,cheeksBoneWidth=0,noseBoneHigh=0,chinBoneLowering=0,cheeksBoneHigh=0,neckThickness=0,cheeksWidth=0,chinBoneLenght=0,jawBoneBackSize=0,nosePeakSize=0,eyesOpening=0,lipsThickness=0,noseWidth=0,eyeBrownForward=0,jawBoneWidth=0,chinBoneSize=0,nosePeakLowering=0,chinHole=0,nosePeakHigh=0},headOverlays={sunDamage={color=0,style=0,opacity=0},blush={color=0,style=0,opacity=0},bodyBlemishes={color=0,style=0,opacity=0},eyebrows={color=0,style=0,opacity=0},beard={color=0,style=0,opacity=0},chestHair={color=0,style=0,opacity=0},lipstick={color=0,style=0,opacity=0},makeUp={color=0,style=0,opacity=0},ageing={color=0,style=0,opacity=0},moleAndFreckles={color=0,style=0,opacity=0},blemishes={color=0,style=0,opacity=0},complexion={color=0,style=0,opacity=0}},eyeColor=-1,model=mp_m_freemode_01}
	}
}

local staffMasks = {
	["1"] = {348, 0}, -- Freddy
	["2"] = {343, 0}, -- Antony
	["3"] = {349, 0}, -- Jack
	["6"] = {335, 0}, -- Avo
	["12"] = {216, 1}, -- Paul
	["55"] = {369, 0}, -- Buu
	["66"] = {290, 0}, -- Fuzza
	["111"] = {302, 0}, -- Kilo
	["50"] = {321, 10}, -- Plumber
}

local customHelmet = {
	["66584"] = {63, 0}
}

local randomStaffMasks = {
	{252, 0},
	{252, 1},
	{252, 2},
}

function SetPedAppearance(ped, appearance)
	local hatData = (HATS[LocalPlayer.state.hat] or false)
	SetPedDefaultComponentVariation(ped)
	ClearAllPedProps(ped)
	if ( not appearance or not appearance.components ) then return end
	local clearRedHat = false
	local clearRedGlasses = false
	if ( hatData and LocalPlayer.state.team == "red" and hatData.clearRedHat ) then
		clearRedHat = true
	end
	if ( hatData and LocalPlayer.state.team == "red" and hatData.clearRedGlasses ) then
		clearRedGlasses = true
	end
	for _, compData in pairs(appearance.components) do
		if ( clearRedHat and compData.component_id == 1 ) then
			SetPedComponentVariation(ped, compData.component_id, 0, 0, 0)
		else
			SetPedComponentVariation(ped, compData.component_id, compData.drawable, compData.texture, 0)
		end
	end
	for _, propData in pairs(appearance.props) do
		if ( clearRedGlasses and propData.prop_id == 1 ) then
			ClearPedProp(ped, propData.prop_id)
		elseif (propData.drawable == -1 or hatData) then
			ClearPedProp(ped, propData.prop_id)
		else
			if propData.prop_id == 0 then
				if customHelmet[tostring(LocalPlayer.state.uid)] then
					SetPedPropIndex(ped, propData.prop_id, customHelmet[tostring(LocalPlayer.state.uid)][1], customHelmet[tostring(LocalPlayer.state.uid)][2], false)
				else
					SetPedPropIndex(ped, propData.prop_id, propData.drawable, propData.texture, false)
				end
			else
				SetPedPropIndex(ped, propData.prop_id, propData.drawable, propData.texture, false)
			end
		end
	end
	SetPedComponentVariation(ped, 2, appearance.hair.style, 0, 0)
	SetPedHairColor(ped, appearance.hair.color, appearance.hair.highlight)
	SetPedEyeColor(ped, appearance.eyeColor)
end

local function replaceMaskComponent(targetComponents, newMaskData)
	for _, compData in pairs(targetComponents) do
		if compData.component_id == 1 then
			compData.drawable = newMaskData[1]
			compData.texture = newMaskData[2]
		end
	end
	return targetComponents
end

local function getRandomStaffMask(targetComponents)
	local newMaskData = randomStaffMasks[math.random(1,#randomStaffMasks)]
	for _, compData in pairs(targetComponents) do
		if compData.component_id == 1 then
			compData.drawable = newMaskData[1]
			compData.texture = newMaskData[2]
		end
	end
	return targetComponents
end

AddStateBagChangeHandler(nil, "player:"..GetPlayerServerId(PlayerId()), function(_, key, value)
	if ( key == "staffMode" and LocalPlayer.state.team ~= nil and LocalPlayer.state.team ~= "none" ) then
		if ( value ) then
			local randomOutfit = math.random(1, #CLOTHES['staff'])
			local customStaffMaskData = staffMasks[tostring(LocalPlayer.state.uid)]
			if customStaffMaskData then
				CLOTHES['staff'][randomOutfit].components = replaceMaskComponent(CLOTHES['staff'][randomOutfit].components, customStaffMaskData)
			else
				--CLOTHES['staff'][randomOutfit].components = getRandomStaffMask(CLOTHES['staff'][randomOutfit].components)
			end
			SetPedAppearance(PlayerPedId(), CLOTHES['staff'][randomOutfit])
		else
			SetPedAppearance(PlayerPedId(), CLOTHES[LocalPlayer.state.team][(LocalPlayer.state.class or 'assault')])
		end
	elseif ( key == "class" and LocalPlayer.state.team ~= 'none' and value ~= 'none' ) then
		SetPedAppearance(PlayerPedId(), CLOTHES[LocalPlayer.state.team][(value)])
	elseif ( key == "hat" and LocalPlayer.state.team ~= 'none') then
		if LocalPlayer.state.staffMode then return end
		SetPedAppearance(PlayerPedId(), CLOTHES[LocalPlayer.state.team][(LocalPlayer.state.class or 'assault')])
	end
end)

local function startCus()
	print(json.encode(exports['fivem-appearance']))
	local config = {
		ped = true,
		headBlend = true,
		faceFeatures = true,
		headOverlays = true,
		components = true,
		props = true,
		allowExit = true,
		tattoos = true,
	}
	exports['fivem-appearance']:startPlayerCustomization(function(appearance)
		if (appearance) then
			print('Saved')
			print(json.encode(appearance))
		else
			print('Canceled')
		end
	end, config)
end

RegisterCommand('cus', function()
	startCus()
end, false)