Citizen.CreateThread(function()
	AddTextEntry("WEAPON_POCKETLIGHT", "Pocket Flashlight")
	AddTextEntry("COMPONENT_PLIGHT_WT", "White Light")
	AddTextEntry("COMPONENT_PLIGHT_UV", "UV Light")
	AddTextEntry("COMPONENT_PLIGHT_RED", "Redlight")
	AddTextEntry("COMPONENT_PLIGHT_PS", "Pocket-sized fleshlight")
    AddTextEntry("COMPONENT_PLIGHT_CAMO_01", "Camo 1")
    AddTextEntry("COMPONENT_PLIGHT_CAMO_02", "Camo 2")
    AddTextEntry("COMPONENT_PLIGHT_CAMO_03", "Camo 3")
    AddTextEntry("COMPONENT_PLIGHT_CAMO_04", "Camo 4")
end)